### ISSUE TITLE
作者您好！进度条的【时间方块】和【时间】不是均匀变化的。

### ISSUE THREAD

**Issue by Miledh** [trazyn/ieaseMusic#104]
进度条的时间方块和时间，有时1秒变动一次，有时2秒变动一次，有时好几秒才变动一次，也就是说每次进度条前进的时间有时是1秒，有时是2秒，有时是好几秒。
看着觉得不协调，怪怪的，就没那么帅了啊！！对了，是在Mac上使用的。
请问可以做成平滑均匀变化的吗？谢谢！

**Comment by trazyn** [comment]
均匀变化需要连续操作`DOM`，对`DOM`操作进行节流，有助于降低`CPU`消耗

2017-12-18 12:11 GMT+08:00 Miledh <notifications@github.com>:

**Comment by Miledh** [comment]
感谢回复！
另外，将来能考虑把进度条的变化调整为每秒变动一下、时间也是一秒一秒地变化吗？
窗口好像是不能调节大小的吧，那么是否可以预先把进度条平均分解，然后一秒前进一格来减少系统消耗呢？一点肤浅的想法，见笑了！

**Comment by Guohjia** [comment]
其实只要监听时间变化事件,算出时间百分比从而设置元素样式即可,1秒钟触发一次,节流不节流影响不大,就算有影响,这么点影响换明显更好的用户体验还是值得的..
