### ISSUE TITLE
打包打代码中NeteaseCloudMusicApi中没有文件

### ISSUE THREAD

**Issue by neko34** [trazyn/ieaseMusic#109]
打包打文件中，NeteaseCloudMusicApi文件夹中没有文件，请问可以直接把你现在的代码直接加进去么？感谢提供这样一个产品

**Comment by neko34** [comment]
好的，我自己解决了，刚刚开始使用，是直接用的npm run dev运行的

发现几个小问题，不知道是不是我是使用编译版本的原因：
1. 我没有找到音量控制的功能？
2. 貌似没有办法最大化，这个界面最大化应该会非常舒服吧？
3. 貌似作者大大总结的其他网站打API接口貌似没有在软件中体现啊？但是在Server代码中的确有明确的接口，是没有使用么？
4. 求出面向多个平台的单曲搜索功能！

**Comment by trazyn** [comment]
```
git submodule init
git submodule update
```
需要安装子模块

**Comment by neko34** [comment]
我直接git clone 你代码中的NeteaseCloudMusicApi文件的，可以播放音乐了，提出的另外几个建议还麻烦大大看一下，很好打作品，Star了

**Comment by trazyn** [comment]
1. 音量控制上下键盘，目前界面放音量条太挤了，需要优化
2. 最大化界面很多元素需要重新适配UI
3. 接口调用以及一些复杂的处理都在`Server`封装了，暴露给UI的是简单的接口
4. 目前一些功能都是依托网易云音乐的，没钱搭自己的后台，因此其他平台的数据没法直接进行管理
