### ISSUE TITLE
emmm...卡死在启动界面

### ISSUE THREAD

**Issue by Hzzone** [trazyn/ieaseMusic#11]
![](http://omoitwcai.bkt.clouddn.com/2017-09-28-%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202017-09-28%20%E4%B8%8B%E5%8D%884.52.05.png)
Mac sierra
从来没打开过..hhh，安装好就这个问题。

**Comment by trazyn** [comment]
官方的api接口有些未知的限制，参考readme里面的海外解锁部分

**Comment by Hzzone** [comment]
@trazyn 可是我在国内啊

**Comment by trazyn** [comment]
@Hzzone 嗯知道，官方接口不仅仅只是限制了海外播放还有一些其他的限制比如高频调用等，所以是建议看看那部分内容的[fengjueming/unblock-NeteastMusic](https://github.com/fengjueming/unblock-NeteastMusic)

加一行hosts解析就行了

**Comment by timelessg** [comment]
同样卡在这里，改host无效

**Comment by trazyn** [comment]
@timelessg 输入这个看看能否正常返回
```
curl http://localhost:8000/login/refresh
```

**Comment by Hzzone** [comment]
@trazyn 突然登进去了？？？

**Comment by trazyn** [comment]
@Hzzone 官方接口在触发某种机制后才会ban你一段时间

**Comment by timelessg** [comment]
curl http://127.0.0.1:8000/login/refresh
{"msg":null,"code":301}
@trazyn

**Comment by trazyn** [comment]
@timelessg 出现这个的时候是不会被卡住的，你可以下一个最新的版本看看，如果卡住的话，devtools里面来个截图给我看看是什么问题导致的
