### ISSUE TITLE
[BUG]体验比上次打开好了，不过还有一些问题

### ISSUE THREAD

**Issue by Yves0** [trazyn/ieaseMusic#110]
- 开启一直 loading
已经一段时间没有用 iease 了，更新之后打开就一直进不去首页，右键可以进去 menu ，退出账号重新登录之后可以正常打开。

- 在个人歌单界面鼠标停在两个 item 之间无法滚动。
![image](https://user-images.githubusercontent.com/17212864/34410154-39be151e-ec09-11e7-8b92-4612563e414b.png)

- Home 歌单问题
在放其他歌单，这里不是应该是日推吗？重启后恢复暂时没有复现。
日推不给查看歌单？点击是暂停继续，虽然可以在播放列表看到
![image](https://user-images.githubusercontent.com/17212864/34410150-3305dd1a-ec09-11e7-87ed-183e602d00e8.png)

- 歌词滚动问题
翻歌词的时候，歌词更新直接滚动到该行了，白向上翻了

- 波浪控件位置有个小 bug
i3wm下可以更改窗口的大小，但改了之后波浪的位置偏了，效果如下
![image](https://user-images.githubusercontent.com/17212864/34410145-27ae79cc-ec09-11e7-8b82-ec31d957a060.png)
![image](https://user-images.githubusercontent.com/17212864/34410139-1e05a03a-ec09-11e7-95bd-15e5a64ebea3.png)

- 缓存
建议是对已经加载过的页面缓存一下，不然老是 loading 体验不好

- 偶尔有些音乐会出现突然停止播放的情况

- menu 可以加个弹出动画

- 没有音量调节吗？

**Comment by Yves0** [comment]
现在感觉差不多可以把 musicbox 换成  iease 了^_^

**Comment by trazyn** [comment]
> 偶尔有些音乐会出现突然停止播放的情况
目前增加了5秒的超时，无搜索结果也会跳到下一首

> 没有音量调节吗？
可以通过键盘的上下键调整音量

**Comment by MuYunyun** [comment]
附议第二点：在个人歌单界面鼠标停在两个 item 之间无法滚动

**Comment by trazyn** [comment]
![user](https://user-images.githubusercontent.com/1774898/47687215-269ec580-dc1a-11e8-9cf5-c2749c7f2fc5.png)
个人页面改了
