### ISSUE TITLE
公司内网

### ISSUE THREAD

**Issue by IAIAE** [trazyn/ieaseMusic#112]
![image](https://user-images.githubusercontent.com/11187162/34442351-7c917a7c-ecfc-11e7-9c3f-b12e38d35b95.png)
有没有一个代理配置选项？或者去包文件哪里改？

**Comment by trazyn** [comment]
目前没有代理设置

**Comment by nondanee** [comment]
只知道网易云的源怎么改
[NeteaseCloudMusicApi/util/util.js](https://github.com/trazyn/NeteaseCloudMusicApi/blob/79ff4cdf41517c36cc89c62687f559f93f302d4f/util/util.js#L21)
Line 21-23
```
      hostname: host,
      method: method,
      path: path,
```
改成
```
      host: <proxy host>,
      port: <proxy port>,
      method: method,
      path: "http://music.163.com" + path,
```

**Comment by Nioty** [comment]
应该可以使用chrome的命令行参数启用代理模式:

`                --proxy-server="foopy:99"
                    Use the HTTP proxy "foopy:99" to load all URLs.

                --proxy-server="socks://foobar:1080"
                    Use the SOCKS v5 proxy "foobar:1080" to load all URLs.

                --proxy-server="socks4://foobar:1080"
                    Use the SOCKS v4 proxy "foobar:1080" to load all URLs.

                --proxy-server="socks5://foobar:66"
                    Use the SOCKS v5 proxy "foobar:66" to load all URLs.
`

**Comment by trazyn** [comment]
Close https://github.com/trazyn/ieaseMusic/commit/41fa408011eabbd58baa2b4dbbaf2a16575d69b6
