### ISSUE TITLE
关于登陆账号后的Bug

### ISSUE THREAD

**Issue by huiyifyj** [trazyn/ieaseMusic#113]
用网易云账号登陆，关闭应用后（`×`或者`quit`），下次再启动时会有个bug，也就是如图。
![after_login](http://huiyifyj.cn/ieaseMusic_bug.jpg)
只有主界面，没有了播放界面。点别的，会一直处于loading<br>
当然，这时候`sign out`的话就可以恢复正常。<br>
这个问题不管是Ubuntu还是windows（自行编译的）下都一样。<br>
这个问题在之前的版本是没问题的，但是现在会因为这样导致出现问题，有时候还会报错。<br>
还有，关于API，希望你能更新下。

**Comment by trazyn** [comment]
更新下到`v1.1.1`官方登录接口添加了`domain`导致登录后无法保存`Cookie`

**Comment by huiyifyj** [comment]
呃，更新了？
没看到。。。

**Comment by trazyn** [comment]
中午刚更新的
