### ISSUE TITLE
Deepin 播放列表界面 TRACK 和 SEARCH 位置不对

### ISSUE THREAD

**Issue by zhdsmy** [trazyn/ieaseMusic#114]
![_ _20180102175654](https://user-images.githubusercontent.com/8348149/34480265-557a98f0-efe6-11e7-80ad-7539175ceecb.png)

**Comment by trazyn** [comment]
看起来是缺少字库 `Roboto`

**Comment by zhdsmy** [comment]
@trazyn 谢谢，确实如此，已解决！
