### ISSUE TITLE
疑似 Bug: Uncaught (in promise) TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by acbetter** [trazyn/ieaseMusic#116]
一个关于启动软件的时候卡在 Please Wait 界面的 Bug
## 复现
在用户已经登录，设置项关闭自动播放（Auto play at started）的时候，启动此 APP，会产生控制台报错

ERROR: Uncaught (in promise) TypeError: Cannot read property '0' of undefined
```
case 12:
    return a.default.autoPlay ? n.default.play() : n.default.song = n.default.playlist.songs[0],
    Q.list = I.data.list,
    A.abrupt('return', Q.list);
```

**Comment by trazyn** [comment]
官方修改了登录以及会话刷新接口，更新到1.1.2
