### ISSUE TITLE
为什么依赖java?

### ISSUE THREAD

**Issue by jouyouyun** [trazyn/ieaseMusic#119]
在 archlinux 里安装时发现依赖java, 这是为什么? 有用到吗?

**Comment by trazyn** [comment]
并没有什么依赖java啊

**Comment by jouyouyun** [comment]
https://aur.archlinux.org/packages/iease-music 里有些依赖 java-environment

**Comment by lsls01** [comment]
这个issue可以关掉了，现在那个AUR的维护者已经去掉了Java依赖
