### ISSUE TITLE
mac osx 10.12.6 触摸板滑动问题

### ISSUE THREAD

**Issue by arthurkiller** [trazyn/ieaseMusic#12]
使用触摸板在主界面上左右滑动圆形视图的体验不太好,有的时候正反颠倒了

而且我用 track pad 滑动的时候,只能往右滑

另外,建议不要置顶窗口,有点奇怪

**Comment by arthurkiller** [comment]
另外, 小的状态栏图标有点奇怪,

**Comment by arthurkiller** [comment]
这个客户端真牛逼, 膜拜了

**Comment by trazyn** [comment]
@arthurkiller 
刚试了下track pad可以滑动啊，不过是向上滑动界面才是像右边移动，晚点我加个选项吧滑动改成自然模式的
窗口置顶可以在设置里面取消的，小图标（非专业人士，不会作图啊😂）也可以隐藏掉的

**Comment by arthurkiller** [comment]
@trazyn 是么, 我这边感觉有点奇怪,就是左右颠倒了,我同事也这样,(不过大家都觉得已经很酷炫了,只有一个人吐槽配色不好看)

图标这个,我可以帮你出图(虽然我也只是一个码农,但是会一点点 PS), 我可以试一下提一个 PR

**Comment by joeybuddy** [comment]
实际上滚动确实反了，首页的专辑列表是自然滚动，和我自己系统设定的非自然滚动是相反的

**Comment by arthurkiller** [comment]
@joeybuddy  哦, 我想起来了, mac 上面的滚动跟鼠标是相反的,是这个原因吧?

**Comment by joeybuddy** [comment]
@arthurkiller 嗯，左右滑动表现和 safari 页面的左右滚动是不一致的，猜测作者是把专辑页面设置固定成自然滚动

**Comment by trazyn** [comment]
@arthurkiller @joeybuddy 代码里面确实是默认的自然滚动，目前旅游中，抽空会增加选项取消自然滚动

**Comment by arthurkiller** [comment]
@trazyn have a nice trip

**Comment by trazyn** [comment]
@arthurkiller thanks

**Comment by agileago** [comment]
mac上当设置拖动为三指拖移的话，客户端图片无法滚动

![image](https://user-images.githubusercontent.com/11799110/31043528-2e4b7a40-a583-11e7-92e0-d02848c343b0.png)

**Comment by trazyn** [comment]
![screen shot 2017-09-30 at 6 35 50 pm](https://user-images.githubusercontent.com/1774898/31045064-4fa7b394-a60e-11e7-8666-27f0a05716be.png)
一直都是三指拖动

**Comment by agileago** [comment]
无法活动
