### ISSUE TITLE
提示TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by x86vk** [trazyn/ieaseMusic#120]
如下图，每隔1-2分钟就弹出来一个

![default](https://user-images.githubusercontent.com/12608529/34811995-b2b6a172-f6de-11e7-9eda-7dbe7fc9b28c.png)

**Comment by huiyifyj** [comment]
你看看是不是你之前的进程没有或关闭彻底。毕竟javascript写的播放器脱离浏览器有点...

**Comment by x86vk** [comment]
emmmmmm 又试图复现了一下，好像在我这边只要登录的时候密码没输对就会这样，就算后面输对了也还是一直弹这个错误。而且在这样运行一阵子之后会卡死，只能`kill -9`杀掉。

**Comment by trazyn** [comment]
Close #172
