### ISSUE TITLE
字体出了点问题

### ISSUE THREAD

**Issue by 0xJacky** [trazyn/ieaseMusic#122]
<img width="852" alt="2018-01-13 1 06 31" src="https://user-images.githubusercontent.com/13096985/34903010-ce09dce8-f862-11e7-9668-f5529ace23a9.png">
<img width="852" alt="2018-01-13 1 06 03" src="https://user-images.githubusercontent.com/13096985/34903012-ce45250a-f862-11e7-936f-e62d4bcc5e24.png">

**Comment by trazyn** [comment]
需要安装 Roboto 字体库

**Comment by 0xJacky** [comment]
好了 谢谢
