### ISSUE TITLE
这界面够sao气，喜欢，有几个问题

### ISSUE THREAD

**Issue by buzai** [trazyn/ieaseMusic#124]
你是不是做设计的啊，一般程序员做绝对很丑。。。
这都是废话，我很想知道那个抖动的波浪线你怎么做的。我用原生做的话会不会很难啊

**Comment by trazyn** [comment]
额 我是做开发的不是做设计的
波浪是canvas写的

**Comment by buzai** [comment]
那你真厉害了，可以给一下代码位置不，我没找到。

**Comment by trazyn** [comment]
utils下面sine.js

**Comment by buzai** [comment]
@trazyn 谢谢了啊
