### ISSUE TITLE
登录bug?

### ISSUE THREAD

**Issue by Passerby** [trazyn/ieaseMusic#127]
![image](https://user-images.githubusercontent.com/1323588/35147626-32548112-fd4a-11e7-9376-9d2b7fdd6ba1.png)

Mac 1.1.2

**Comment by kenshinji** [comment]
你也是用邮箱登录的么？我用邮箱登录就遇到这个问题

**Comment by trazyn** [comment]
目前只能用手机登录的

**Comment by trazyn** [comment]
Close #172
