### ISSUE TITLE
首页有时候加载不全

### ISSUE THREAD

**Issue by dai875939260** [trazyn/ieaseMusic#128]
首页的最下面播放条有时候出不来，重新登录下就好了。

![image](https://user-images.githubusercontent.com/6057326/35190168-4e577516-fe96-11e7-9676-141a2bf7f31b.png)

**Comment by trazyn** [comment]
更新下版本，老版本cookie设置有问题，会导致失效
```
rm -rf ~/Library/Application\ Support/iease-music/
brew cask install ieasemusic
```
