### ISSUE TITLE
窗口无法放大缩小；永远都是置顶显示

### ISSUE THREAD

**Issue by aizhimou** [trazyn/ieaseMusic#134]
系统是ubuntu desktop 16.04
1. 软件窗口无法拖大和缩小
2. 软件窗口永远都是自动置顶显示，和别的窗口重叠时，激活别的窗口，这个软件也会一直显示在最前端
3. 实在是太好看了，也很好用！

**Comment by trazyn** [comment]
设置里面可以取消always on top
