### ISSUE TITLE
在 Gnome 下启动后会在启动器新开一个图标

### ISSUE THREAD

**Issue by xcffl** [trazyn/ieaseMusic#141]
在 Gnome 下启动 ieaseMusic 后，ieaseMusic 不会使用原本固定在启动器上的图标，而是会新开一个图标（也许是 Electron 程序的默认图标？）。如果没有固定的话，也不会使用 ieaseMusic 自带的图标。

解决方法很简单，在 ieaseMusic.desktop 的 `[Desktop Entry]` 加上一行
`StartupWMClass=ieaseMusic`
即可。
但不知道对于 electron 程序来说应该怎么加。
希望能修复一下。

**Comment by xcffl** [comment]
根据这个手册，应该是在 `package.json` 的 `"build"` -> `"linux"` 下加上一行
`"StartupWMClass": "ieaseMusic"`

**Comment by trazyn** [comment]
这个是`electron-builder`的问题
https://github.com/electron-userland/electron-builder/issues/2098
