### ISSUE TITLE
archlinux  + gnome3，有时候窗口大小不能调。

### ISSUE THREAD

**Issue by yueduz** [trazyn/ieaseMusic#146]

**Comment by trazyn** [comment]
窗口大小是固定的

**Comment by yueduz** [comment]
但是我有一次调了大小，在弹出错误警告后。

**Comment by trazyn** [comment]
能调整窗口大小就是bug了

**Comment by yueduz** [comment]
播放列表太小

衣带渐宽人渐悔 <notifications@github.com> 于 2018年2月28日周三 13:15写道：

**Comment by xcffl** [comment]
关闭窗口后（因为 Linux 下没有实现 Frameless）再从任务栏切换出就可调整大小了。

**Comment by trazyn** [comment]
：）
不能调节窗口大小
