### ISSUE TITLE
提一个显示bug

### ISSUE THREAD

**Issue by fh345392977** [trazyn/ieaseMusic#151]
图中这一块的背景色貌似是随机的，有时候会是白色背景，右上角的三个操作按钮就看不见了。。。
![image](https://user-images.githubusercontent.com/16329330/37387429-45b9457c-2797-11e8-94ca-5f6b2e2db716.png)

**Comment by huiyifyj** [comment]
这不算bug，颜色重合了而已。因为图标的颜色被写死了，所以无法根据背景色改变而已。

**Comment by trazyn** [comment]
颜色值是通过歌曲封面图片色值计算出来的，没有做对比值所以有时候会遮住背景色
