### ISSUE TITLE
js

### ISSUE THREAD

**Issue by softshenCN** [trazyn/ieaseMusic#152]

**Comment by softshenCN** [comment]
会报错，提示两个对话框

**Comment by trazyn** [comment]
linux？mac？截图？

**Comment by lixiangzhong** [comment]
![20180320144218](https://user-images.githubusercontent.com/10345096/37639611-1e3e9ee2-2c4d-11e8-9e3f-125d3e5dbad9.png)


我也会弹这个  linux(deepin15.5)

**Comment by Pesdestrian** [comment]
一样的错误

**Comment by trazyn** [comment]
Close #172
