### ISSUE TITLE
酷酷非常酷,但是用起来并不高效.

### ISSUE THREAD

**Issue by yueduz** [trazyn/ieaseMusic#156]
所以装上用了几次后还是用网页版了.一点建议,过多的动画特效就只是酷酷非常酷,但是用起来并不高效.

**Comment by mengyaoss77** [comment]
而且创建的歌单看不全 没有滑动条。。

**Comment by dale0525** [comment]
1. 没有全局快捷键
2. 每日推荐歌单需要重启才能刷新
3. 似乎没有缓存？
4. 经常在加载某首歌的时候就永远卡死了，也不努力重新加载，也不跳下一首

**Comment by Sherlock-Holo** [comment]
鼠标用户的体验就不是用户体验了？？？

另外装了后进了几个页面发现没有一下子就找到返回按钮，鼠标的后退键无用

好看，不实用
