### ISSUE TITLE
“ieaseMusic-0.0.3-mac.dmg” can’t be opened because it is from an unidentified developer.

### ISSUE THREAD

**Issue by SLRXXX** [trazyn/ieaseMusic#16]
RT

**Comment by howie6879** [comment]
在设置里开启允许权限

**Comment by trazyn** [comment]
![screen shot 2017-09-29 at 1 23 32 pm](https://user-images.githubusercontent.com/1774898/31001865-675e35d0-a519-11e7-8325-fb9f5e51f8dd.png)
设置里面设置成 `anywhere` 就好了
