### ISSUE TITLE
问个问题，可能比较弱：网易已经有windows和mac的桌面端，咱们这个程序比网易的好在什么地方呢？

### ISSUE THREAD

**Issue by lushibi** [trazyn/ieaseMusic#164]
如题。
当然，源码可以用来学习，但抛开这点的话，难道仅仅是界面炫点？

**Comment by sunnysnake** [comment]
刚刚用了一下。 听歌方面还不错，免费听SQ音质 ，多平台聚合是特点。短板是没有全局控制，跟系统的控制接口还没有衔接上，体验上差了点。再接再厉
