### ISSUE TITLE
Mac客户端--一直在加载，从来没进去过。。。

### ISSUE THREAD

**Issue by beyond510** [trazyn/ieaseMusic#165]
我提这个问题的时候是1.1.2 我今天更新到了1.1.5这个问题还是存在。
控制台里没内容,10083端口没有其它占用。

<img width="738" alt="wx20180524-165848 2x" src="https://user-images.githubusercontent.com/28379540/40475668-b52827d8-5f74-11e8-8aa9-64b979c3dd2c.png">

**Comment by trazyn** [comment]
没有任何报错的话，打开控制台然后刷新看看第一个请求是否完成

**Comment by SunnyWind** [comment]
localhost:10086/api/home这个请求pending
