### ISSUE TITLE
听歌的时候会无法加载跳很多框框

### ISSUE THREAD

**Issue by ghost** [trazyn/ieaseMusic#170]
<img width="418" alt="2018-06-11 12 30 34" src="https://user-images.githubusercontent.com/39001088/41212849-a85e130c-6d73-11e8-927f-876762c2d281.png">
<img width="416" alt="2018-06-11 12 30 43" src="https://user-images.githubusercontent.com/39001088/41212854-aa22299e-6d73-11e8-811f-7b71e203a68d.png">

**Comment by myhoco** [comment]
不止这几个，这是启动的时候弹出的，听歌时经常会跳出5-6个这样的框框
