### ISSUE TITLE
除了评论和歌词，可以增加一个只看封面的选项么？

### ISSUE THREAD

**Issue by ustchcl** [trazyn/ieaseMusic#171]
![tim 20180614182349](https://user-images.githubusercontent.com/14542541/41406876-4b4e2abe-7000-11e8-899b-b97b9a7c0882.png)
纯音乐的时候显示Nothing...有点丑。

**Comment by trazyn** [comment]
![screen shot 2018-06-30 at 6 03 22 pm](https://user-images.githubusercontent.com/1774898/42124134-f38ad4a2-7c8f-11e8-99fd-31737f41f917.png)

**Comment by ustchcl** [comment]
赞！
