### ISSUE TITLE
关于密码输错的Bug

### ISSUE THREAD

**Issue by howie6879** [trazyn/ieaseMusic#172]
![wechatimg3090](https://user-images.githubusercontent.com/17047388/41453887-0730b2f2-70aa-11e8-95ca-11f65d9b9b49.jpeg)

**Comment by trazyn** [comment]
这个BUG看到提了很多次，就是不知道怎么重现

**Comment by howie6879** [comment]
我发现只要把密码输错 这个就会出现 我试了几次都这样 密码正确就不会

**Comment by trazyn** [comment]
是的，登录失败就会有这个，刚修复了
