### ISSUE TITLE
ubuntu下出现的问题

### ISSUE THREAD

**Issue by StudyForMe** [trazyn/ieaseMusic#178]
1.第一次安装后正常启动，但是在我重启后无法打开，一直转圈，过了一段时间后才打开
2.打开的播放器与应用图标不兼容，dash里面看起来有两个图标
3.如果关闭播放器的话仍在后台播放，这个怎么解决
4.依旧是一个很好的播放器，加油

**Comment by oneforever** [comment]
是的,关闭播放器以后还会在后台播放音乐,重新打开播放器的时候就会有错误哦

**Comment by StudyForMe** [comment]
准备在下一次更新中解决这个问题吗

**Comment by trazyn** [comment]
yes

**Comment by oneforever** [comment]
hopeful

**Comment by trazyn** [comment]
![screenshot from 2018-06-26 00-00-11](https://user-images.githubusercontent.com/1774898/41861461-f0a18a84-78d3-11e8-9b7b-058fc34d4de5.png)
