### ISSUE TITLE
首页图片拖拽问题

### ISSUE THREAD

**Issue by chen8160** [trazyn/ieaseMusic#18]
首先感谢老铁！播放器做的很赞！

用macbook touchpad 三指拖拽首页图片的时候，发生了如下情况。图片被拖拽了，小问题。

![image](https://user-images.githubusercontent.com/8757351/31001819-6078b5f2-a49b-11e7-9bb4-17742546072b.png)

还有两个小问题：

1. 个人觉得菜单中字体偏细，看不是很清楚。

2. 一直固定显示在其他应用之上有些不适应，可以加个偏好设置

希望这个播放器能做下去！功能更加完善！

**Comment by trazyn** [comment]
嗯，这些细节确实没空滤到，谢谢反馈了，后续会进行调整
