### ISSUE TITLE
v1.1.6 sha256 未更新

### ISSUE THREAD

**Issue by LyonUp** [trazyn/ieaseMusic#182]
==> Satisfying dependencies
==> Downloading https://github.com/trazyn/ieaseMusic/releases/download/v1.1.6/ie
######################################################################## 100.0%
==> Verifying checksum for Cask ieasemusic
==> Note: running "brew update" may fix sha256 checksum errors
Error: Checksum for Cask 'ieasemusic' does not match.

Expected: 4be84837e9bf11967b197690fc1626e0d74b8ee0863b7748acc15c23223263c6
Actual:   16b9eeb49e5c4a13cfadda0d674991fbf178b6c03a9d4993496157812fe38bd2
File:     /Users/lihang/Library/Caches/Homebrew/Cask/ieasemusic--1.1.6.dmg

**Comment by trazyn** [comment]
没有提交1.16的homebrew
