### ISSUE TITLE
不能登录网易云，一个小BUG,拜托作者修复一下，还有可以让其不要总是显示在前端吗，要看其他窗口还得缩小播放器。

### ISSUE THREAD

**Issue by aikeji365** [trazyn/ieaseMusic#199]
mac客户端是这样子的，版本1.2.0

**Comment by trazyn** [comment]
在设置里面可以取消

**Comment by aikeji365** [comment]
好的




| |
邮箱：aikeji365@163.com
|

签名由 网易邮箱大师 定制

在2018年07月06日 12:22，trazyn 写道：

在设置里面可以取消

**Comment by aikeji365** [comment]
不能登录能解决吗




| |
邮箱：aikeji365@163.com
|

签名由 网易邮箱大师 定制

在2018年07月13日 23:56，aikeji365 写道：
好的




| |
邮箱：aikeji365@163.com
|

签名由 网易邮箱大师 定制

在2018年07月06日 12:22，trazyn 写道：

在设置里面可以取消

**Comment by trazyn** [comment]
手机号一直能登录

**Comment by aikeji365** [comment]
我回车登录，然后软件就卡在空白窗口了




| |
邮箱：aikeji365@163.com
|

签名由 网易邮箱大师 定制

在2018年07月13日 23:58，trazyn 写道：

手机号一直能登录

**Comment by trazyn** [comment]
登录一直`Loading`？

**Comment by aikeji365** [comment]
我打个截图给你




| |
邮箱：aikeji365@163.com
|

签名由 网易邮箱大师 定制

在2018年07月14日 00:01，trazyn 写道：

登录一直Loading？

**Comment by trazyn** [comment]
看看控制台的内容

**Comment by aikeji365** [comment]
明天我发个动态截图给你




| |
邮箱：aikeji365@163.com
|

签名由 网易邮箱大师 定制

在2018年07月14日 00:03，trazyn 写道：

看看控制台的内容

**Comment by trazyn** [comment]
在登录界面打开控制台`CMD+ALT+I`，然后进行登录，如果是登录请求一直`pending`，可以按照`README`中`UNBLOCK`部分修改`hosts`文件，增加：
```
158.199.142.239 music.163.com
```
如果有红色错误打印，可以截图贴上来看看

**Comment by trazyn** [comment]
可以开啊 国内更新会很慢了 另外几个曲库质量比较差了

**Comment by lcx10086** [comment]
![image](https://user-images.githubusercontent.com/26214474/42733001-9c2faed8-885d-11e8-85bf-24e803477ccd.png)
登录后界面空白的

**Comment by trazyn** [comment]
看看控制台的打印内容

**Comment by lcx10086** [comment]
{"playlist":{"subscribers":[],"subscribed":false,"creator":{"defaultAvatar":false,"province":330000,"authStatus":0,"followed":false,"avatarUrl":"http://p1.music.126.net/66a2_BEYdKG0EmGe7vA_3w==/18494885092508125.jpg","accountStatus":0,"gender":1,"city":330100,"birthday":-2209017600000,"userId":392507468,"userType":0,"nickname":"成-忄","signature":"","description":"","detailDescription":"","avatarImgId":18494885092508125,"backgroundImgId":2002210674180199,"backgroundUrl":"http://p1.music.126.net/VTW4vsN08vwL3uSQqPyHqg==/2002210674180199.jpg","authority":0,"mutual":false,"expertTags":null,"experts":null,"djStatus":0,"vipType":0,"remarkName":null,"avatarImgIdStr":"18494885092508125","backgroundImgIdStr":"2002210674180199","avatarImgId_str":"18494885092508125"},"tracks":[],"trackIds":[],"ordered":false,"tags":[],"adType":0,"trackNumberUpdateTime":0,"cloudTrackCount":0,"subscribedCount":0,"description":null,"status":0,"coverImgId":3397490930543093,"createTime":1483365856683,"updateTime":1483365856683,"specialType":5,"trackUpdateTime":1483365858802,"trackCount":0,"highQuality":false,"commentThreadId":"A_PL_0_556813489","playCount":0,"privacy":0,"userId":392507468,"newImported":false,"coverImgUrl":"http://p3.music.126.net/EWC8bPR8WW9KvhaftdmsXQ==/3397490930543093.jpg","name":"成-忄喜欢的音乐","id":556813489,"shareCount":0,"commentCount":0},"code":200}

有很长一段，这只是一部分

**Comment by aikeji365** [comment]
这是什么




| |
邮箱：aikeji365@163.com
|

签名由 网易邮箱大师 定制

在2018年07月15日 18:43，lcx10086 写道：

{"playlist":{"subscribers":[],"subscribed":false,"creator":{"defaultAvatar":false,"province":330000,"authStatus":0,"followed":false,"avatarUrl":"http://p1.music.126.net/66a2_BEYdKG0EmGe7vA_3w==/18494885092508125.jpg","accountStatus":0,"gender":1,"city":330100,"birthday":-2209017600000,"userId":392507468,"userType":0,"nickname":"成-忄","signature":"","description":"","detailDescription":"","avatarImgId":18494885092508125,"backgroundImgId":2002210674180199,"backgroundUrl":"http://p1.music.126.net/VTW4vsN08vwL3uSQqPyHqg==/2002210674180199.jpg","authority":0,"mutual":false,"expertTags":null,"experts":null,"djStatus":0,"vipType":0,"remarkName":null,"avatarImgIdStr":"18494885092508125","backgroundImgIdStr":"2002210674180199","avatarImgId_str":"18494885092508125"},"tracks":[],"trackIds":[],"ordered":false,"tags":[],"adType":0,"trackNumberUpdateTime":0,"cloudTrackCount":0,"subscribedCount":0,"description":null,"status":0,"coverImgId":3397490930543093,"createTime":1483365856683,"updateTime":1483365856683,"specialType":5,"trackUpdateTime":1483365858802,"trackCount":0,"highQuality":false,"commentThreadId":"A_PL_0_556813489","playCount":0,"privacy":0,"userId":392507468,"newImported":false,"coverImgUrl":"http://p3.music.126.net/EWC8bPR8WW9KvhaftdmsXQ==/3397490930543093.jpg","name":"成-忄喜欢的音乐","id":556813489,"shareCount":0,"commentCount":0},"code":200}

有很长一段，这只是一部分

**Comment by aikeji365** [comment]
我不会用。。




| |
邮箱：aikeji365@163.com
|

签名由 网易邮箱大师 定制

在2018年07月15日 18:44，aikeji365 写道：
这是什么




| |
邮箱：aikeji365@163.com
|

签名由 网易邮箱大师 定制

在2018年07月15日 18:43，lcx10086 写道：

{"playlist":{"subscribers":[],"subscribed":false,"creator":{"defaultAvatar":false,"province":330000,"authStatus":0,"followed":false,"avatarUrl":"http://p1.music.126.net/66a2_BEYdKG0EmGe7vA_3w==/18494885092508125.jpg","accountStatus":0,"gender":1,"city":330100,"birthday":-2209017600000,"userId":392507468,"userType":0,"nickname":"成-忄","signature":"","description":"","detailDescription":"","avatarImgId":18494885092508125,"backgroundImgId":2002210674180199,"backgroundUrl":"http://p1.music.126.net/VTW4vsN08vwL3uSQqPyHqg==/2002210674180199.jpg","authority":0,"mutual":false,"expertTags":null,"experts":null,"djStatus":0,"vipType":0,"remarkName":null,"avatarImgIdStr":"18494885092508125","backgroundImgIdStr":"2002210674180199","avatarImgId_str":"18494885092508125"},"tracks":[],"trackIds":[],"ordered":false,"tags":[],"adType":0,"trackNumberUpdateTime":0,"cloudTrackCount":0,"subscribedCount":0,"description":null,"status":0,"coverImgId":3397490930543093,"createTime":1483365856683,"updateTime":1483365856683,"specialType":5,"trackUpdateTime":1483365858802,"trackCount":0,"highQuality":false,"commentThreadId":"A_PL_0_556813489","playCount":0,"privacy":0,"userId":392507468,"newImported":false,"coverImgUrl":"http://p3.music.126.net/EWC8bPR8WW9KvhaftdmsXQ==/3397490930543093.jpg","name":"成-忄喜欢的音乐","id":556813489,"shareCount":0,"commentCount":0},"code":200}

有很长一段，这只是一部分

**Comment by lcx10086** [comment]
我在终端启动应用，登录部分的输出，系统ubuntu18.04
{"playlist":{"subscribers":[],"subscribed":false,"creator":{"defaultAvatar":false,"province":330000,"authStatus":0,"followed":false,"avatarUrl":"http://p1.music.126.net/66a2_BEYdKG0EmGe7vA_3w==/18494885092508125.jpg","accountStatus":0,"gender":1,"city":330100,"birthday":-2209017600000,"userId":392507468,"userType":0,"nickname":"成-忄","signature":"","description":"","detailDescription":"","avatarImgId":18494885092508125,"backgroundImgId":2002210674180199,"backgroundUrl":"http://p1.music.126.net/VTW4vsN08vwL3uSQqPyHqg==/2002210674180199.jpg","authority":0,"mutual":false,"expertTags":null,"experts":null,"djStatus":0,"vipType":0,"remarkName":null,"backgroundImgIdStr":"2002210674180199","avatarImgIdStr":"18494885092508125","avatarImgId_str":"18494885092508125"},"tracks":[],"trackIds":[],"userId":392507468,"coverImgUrl":"http://p4.music.126.net/EWC8bPR8WW9KvhaftdmsXQ==/3397490930543093.jpg","trackCount":0,"playCount":0,"coverImgId":3397490930543093,"createTime":1483365856683,"updateTime":1483365856683,"privacy":0,"newImported":false,"specialType":5,"trackUpdateTime":1483365858802,"highQuality":false,"commentThreadId":"A_PL_0_556813489","status":0,"ordered":false,"tags":[],"trackNumberUpdateTime":0,"adType":0,"description":null,"subscribedCount":0,"cloudTrackCount":0,"name":"成-忄喜欢的音乐","id":556813489,"shareCount":0,"commentCount":0},"code":200}

**Comment by trazyn** [comment]
@lcx10086 `CMD+SHIFT+I`的控制台
![screen shot 2018-07-15 at 6 59 44 pm](https://user-images.githubusercontent.com/1774898/42733278-402aefcc-8861-11e8-8023-d3ffce35fe77.png)

**Comment by lcx10086** [comment]
![image](https://user-images.githubusercontent.com/26214474/42733315-f7a4af30-8861-11e8-9ebd-0c13c80bbc42.png)
![image](https://user-images.githubusercontent.com/26214474/42733318-066f365c-8862-11e8-9337-4b993a9fa0be.png)
不知道CMD键是什么，但在面板中找到控制台

**Comment by trazyn** [comment]
你的账号ID是多少啊？
![screen shot 2018-07-15 at 7 15 24 pm](https://user-images.githubusercontent.com/1774898/42733408-7a0fd516-8863-11e8-8545-60782d54c620.png)
登录到云音乐我的主页上看的到

**Comment by trazyn** [comment]
你的账号看起来是没有任何的收藏歌曲，“我的喜欢的音乐”是空的，所以才会出现这个错误

**Comment by lcx10086** [comment]
![image](https://user-images.githubusercontent.com/26214474/42733536-5a9093c2-8865-11e8-8c35-2eccfa9b19fc.png)

**Comment by trazyn** [comment]
你的账号是我喜欢的音乐是空的所以打开会报错，这个后面修复，随便加首到喜欢登录就不会报错了

**Comment by lcx10086** [comment]
确实是，多谢大佬
