### ISSUE TITLE
macos10.13打开直接报错😢

### ISSUE THREAD

**Issue by durongzhang** [trazyn/ieaseMusic#20]
![image](https://user-images.githubusercontent.com/15725537/31002809-535d5f00-a4b2-11e7-9b74-04bfe1d1ef8e.png)
很想尝试下，结果被拒之门外

**Comment by trazyn** [comment]
触发了官方API某种神秘机制，短时间内被ban，改下hosts
https://github.com/fengjueming/unblock-NeteastMusic

**Comment by durongzhang** [comment]
解决了，软件很棒
