### ISSUE TITLE
最beautiful的音乐播放器，但是老哥能不能把播放器的logo设计得更有自己的个性点

### ISSUE THREAD

**Issue by peanutDD** [trazyn/ieaseMusic#203]
最beautiful的音乐播放器，但是老哥能不能把播放器的logo设计得更有自己的个性，打开mac后，看见那个图标和iTunes很像，瞬间少了那么一点逼格！

**Comment by trazyn** [comment]
我只是个程序员不会设计啊

**Comment by peanutDD** [comment]
这个图标不错哟，给楼上加鸡腿！
