### ISSUE TITLE
很好的播放器, 请问这播放音乐是不是只能听乐音不能下载音乐, 如何可以下载应该怎么下载?

### ISSUE THREAD

**Issue by Mourris** [trazyn/ieaseMusic#205]
很好的播放器, 请问这播放音乐是不是只能听乐音不能下载音乐, 如何可以下载应该怎么下载? 还有能不能搞一个中文界面呀? 英文的看起来好难受呀....

**Comment by trazyn** [comment]
感觉没什么必要所以没加这个功能

**Comment by Mourris** [comment]
不能下载歌曲到本地就算了, 但是可以弄一个中文版不?
