### ISSUE TITLE
请问哪里可以注册啊？？？

### ISSUE THREAD

**Issue by Bubbab123** [trazyn/ieaseMusic#209]
找到了登陆界面 但不知道哪里去sign up啊？找了半天也找不到？
<img width="868" alt="2018-07-09 5 24 18" src="https://user-images.githubusercontent.com/32544961/42472835-4d4d0de8-839d-11e8-8f6a-ee9cede6a24c.png">

**Comment by trazyn** [comment]
额 是用网易云音乐帐号登录的 你用手机注册个网易云音乐的帐号就好

**Comment by trazyn** [comment]
http://music.163.com/

**Comment by Bubbab123** [comment]
那完了 我用的是微博注册的

**Comment by trazyn** [comment]
绑定手机号

**Comment by Bubbab123** [comment]
或者有没有方式可以迁移我的账号歌单到另一个账号里呢？

**Comment by Bubbab123** [comment]
那个 国外新注册的手机号好像登陆不了是吧

**Comment by Bubbab123** [comment]
很难受 客服都不行

**Comment by trazyn** [comment]
我也是国外手机号登录的

**Comment by Bubbab123** [comment]
不行啊

**Comment by trazyn** [comment]
国外手机号登录前面加国家码

**Comment by Bubbab123** [comment]
还是不行
网页版网易云登进去了

**Comment by trazyn** [comment]
![untitled](https://user-images.githubusercontent.com/1774898/42489082-980228ca-843b-11e8-9f68-49e3740a079e.png)

**Comment by trazyn** [comment]
现在好像不能绑定国外手机号了

**Comment by trazyn** [comment]
现在估计只能伪造请求绑定国外手机号了

**Comment by Bubbab123** [comment]
gg了是吗

**Comment by trazyn** [comment]
是啊

**Comment by Bubbab123** [comment]
能做一个微博登录吗？多谢了🙏

**Comment by trazyn** [comment]
@Bubbab123 云音乐的网站上可以使用国外手机号注册

**Comment by Bubbab123** [comment]
我新注册的国外手机号，在网易云音乐的官网上登录成功了。但在ieaseMusic里登录不上

**Comment by trazyn** [comment]
登录那里有加上国家码的 @Bubbab123 比如美国号码，前面加+1

**Comment by Bubbab123** [comment]
+1了还是不行

**Comment by trazyn** [comment]
我也是用的国外的手机号登录的，截图看看控制台的输出

**Comment by trazyn** [comment]
1.2.9微信登录
