### ISSUE TITLE
打开一直please wait 转圈圈

### ISSUE THREAD

**Issue by insertSweat** [trazyn/ieaseMusic#21]
![image](https://user-images.githubusercontent.com/13713662/31007057-c72f7a32-a4c4-11e7-9aef-e3358fd5dcac.png)
如图 系统osx 10.12.4

**Comment by trazyn** [comment]
参考#20 换个host就好

**Comment by insertSweat** [comment]
改了host，没啥用还是一直转圈

**Comment by trazyn** [comment]
看看host修改生效没有
