### ISSUE TITLE
请问支持chromebook上安装么？？

### ISSUE THREAD

**Issue by lee2333** [trazyn/ieaseMusic#214]
我的chromebook plus最近支持了安装linux，是arm架构的，不知道支不支持使用这个软件？有点小白，试着装了几个版本都没成功，不知道是选错版本了还是不支持使用，谢谢。

**Comment by trazyn** [comment]
`Electron`目前还不支持在`Chrome OS`上运行，可以在`Linux`上运行

**Comment by lee2333** [comment]
请问arm64位的系统应该用哪个版本呢？？

**Comment by trazyn** [comment]
`arm64`是`CPU`架构，`Electron`能否运行和操作系统相关，你装的`Linux`是什么发行版

**Comment by lee2333** [comment]
貌似是Debian，那就应该执行sudo dpkg -i ieaseMusic-1.2.5-linux-amd64.deb么？好像提示不适配我的系统。

trazyn <notifications@github.com> 於 2018年7月13日 週五 下午9:20寫道：

**Comment by trazyn** [comment]
桌面环境`Gnome`的话，下载`deb`文件双击都有安装提示，不行可以下一个`Appimage`格式的试试
