### ISSUE TITLE
[ArchLinux with node 10.6.0, npm 6.2.0] SyntaxError: Unexpected token import for main.js 

### ISSUE THREAD

**Issue by heavysink** [trazyn/ieaseMusic#219]
环境如标题。
编译一切正常，但是启动的时候main.js一直报SyntaxError: Unexpected token import.
Uncaught Exception:
/opt/ieaseMusic/main.js:2
import path from 'path';
^^^^^^

尝试着把它们改成const path = require("path") 貌似能成功，但是修改量太大了（所有import都得改）。
由于一些特殊原因，只能通过手动编译安装，请问有没有什么办法，谢谢！

**Comment by trazyn** [comment]
你这是依赖装的有问题 删除 node_modules目录然后重新安装
