### ISSUE TITLE
Alfred 操作感觉反应不够快

### ISSUE THREAD

**Issue by JustYummy** [trazyn/ieaseMusic#220]
在使用时候想要切换下一首歌
输入```mm next```
但因为反应时间太长(差不多一两秒)，才把默认的暂停选项换成下一首歌的
所以回车操作的时候是暂停，而不是下一首
如下图：
<img width="541" alt="2018-07-21 10 09 29" src="https://user-images.githubusercontent.com/16171813/43031143-32e1939a-8cce-11e8-845e-196ee6b23bf7.png">

**Comment by trazyn** [comment]
可以修改`Script Filter`的`Run behavior`，改成第一个:
![screen shot 2018-07-21 at 2 20 34 pm](https://user-images.githubusercontent.com/1774898/43032771-5bfd5552-8cf1-11e8-8342-0eff4ac4e5ad.png)

**Comment by trazyn** [comment]
https://github.com/trazyn/alfred-ieasemusic/releases/tag/v1.0.2
