### ISSUE TITLE
mac一直初始化

### ISSUE THREAD

**Issue by fangjidezhu** [trazyn/ieaseMusic#224]
mac10.13.6，打开后一直旋转
![7 -23-2018 19-27-18](https://user-images.githubusercontent.com/8556903/43074116-bcc78880-8eae-11e8-8ac2-1f02fb23e2b2.gif)

**Comment by trazyn** [comment]
可以试着改下hosts文件

**Comment by fangjidezhu** [comment]
之前已经尝试配置了这个hosts 
```hosts
158.199.142.239 music.163.com p1.music.126.net p2.music.126.net p3.music.126.net p4.music.126.net
```

**Comment by trazyn** [comment]
还是高频访问限制那就只能等段时间了

**Comment by fangjidezhu** [comment]
好的，感谢
