### ISSUE TITLE
应该开启时，请求地址为localhost:8000

### ISSUE THREAD

**Issue by fh345392977** [trazyn/ieaseMusic#23]
![image](https://user-images.githubusercontent.com/16329330/31011250-32aa21e6-a4d3-11e7-8581-9c1e0cded8d1.png)

**Comment by trazyn** [comment]
参考#20 改下host

**Comment by fh345392977** [comment]
解决了，是我nginx支配了端口，改了端口就好了

**Comment by trazyn** [comment]
现在可以在设置里面改端口号的
