### ISSUE TITLE
Linux 可以增加一个隐藏菜单栏的选项吗？

### ISSUE THREAD

**Issue by imzf** [trazyn/ieaseMusic#24]
如题，挺讨厌菜单栏的

**Comment by trazyn** [comment]
右键的菜单？

**Comment by imzf** [comment]
@trazyn 就是标题栏下的菜单
![default](https://user-images.githubusercontent.com/3401994/31042084-c9d200e8-a5d2-11e7-9095-fbb955b62333.png)

**Comment by trazyn** [comment]
Ubuntu的gnome上是不显示这个，有空我加个选项吧

**Comment by Awesomepig** [comment]
呃,本来想声援一下,说unity下面菜单栏也挺丑的,但是,考虑到马上要换gnome了,就算了.
![2017-10-12 15-04-40](https://user-images.githubusercontent.com/6083234/31483391-bc7eb022-af5e-11e7-8ff8-be0af0ea85a4.png)

**Comment by trazyn** [comment]
1.0.1 已经去除了顶部的菜单
