### ISSUE TITLE
播放曲目错乱

### ISSUE THREAD

**Issue by lcl2539** [trazyn/ieaseMusic#243]
您好，我在使用时发现播放毛不易的《不染》时播放的实际是《无问》，暂时没有发现其他同样的情况，不知是什么情况？

**Comment by trazyn** [comment]
歌单ID多少？

**Comment by theFool32** [comment]
42493198

**Comment by trazyn** [comment]
说下音源的获取，首先是QQ音乐的高品质，没找到的时候同时并发在其他几个曲库（网易，QQ，虾米等）里面查询模糊拼配歌名和歌手名（网易的是ID匹配），取第一个的返回结果。

你碰到的这种情况2种可能：
1. QQ高品质拿到的是`live`版本
2. 相同网络环境下，其他曲库先返回了

具体是那种情况可以打开控制台输入`$('audio')`看看`src`是哪个源
![screen shot 2018-08-04 at 8 45 18 pm](https://user-images.githubusercontent.com/1774898/43676645-8474b070-9827-11e8-9220-5c18f7c7542b.png)

其他：目前酷狗曲库里面比较多的伴奏和`live`，可以在设置里面关闭
