### ISSUE TITLE
微信扫码登陆后界面空白

### ISSUE THREAD

**Issue by yiyulong** [trazyn/ieaseMusic#245]

**Comment by trazyn** [comment]
你的账号绑定过微信么？

**Comment by Andy880915** [comment]
我也遇到同樣問題，確定有綁微信的
版本：1.3.0
系統：10.13.6

**Comment by trazyn** [comment]
@Andy880915 控制台有错误输出么？

**Comment by Andy880915** [comment]
@trazyn 我是小白 能教教我怎麼看嗎 很希望能幫上您改善的
我開了developer tools看到有個報錯 不知是不是這個啊？
![2018-08-07 4 57 26](https://user-images.githubusercontent.com/14562646/43775678-231e80de-9a80-11e8-8355-874f98b6b9a2.png)

**Comment by trazyn** [comment]
@Andy880915 你这个验证还没刷出来，扫码登录，然后看看控制台的输出内容
![screen shot 2018-08-07 at 11 40 13 pm](https://user-images.githubusercontent.com/1774898/43786467-3fe85526-9a9b-11e8-8f64-44cd6044d942.png)

**Comment by Andy880915** [comment]
@trazyn 是呀 所謂空白就是他不會出來 等超過五分鐘還是原本的圖樣

**Comment by trazyn** [comment]
额 这个就和网络情况有关了，我在公司也刷不出来，但是家里网络ok
还有unblock以后也出不来

**Comment by Andy880915** [comment]
@trazyn 了解....我是在台灣的使用者 
網速500M下載/300M上傳應該是沒問題 可能就是unblock的緣故吧....
可惜了沒辦法登入 網易雲也沒辦法綁台灣手機號
謝謝您了

**Comment by trazyn** [comment]
先注释unblock然后扫码登录，在去掉unblock，目前只能这么操作了
后面可能要改下unblock的转发规则
