### ISSUE TITLE
在一次闪退后就无法进入无限加载

### ISSUE THREAD

**Issue by datou1996** [trazyn/ieaseMusic#246]
反复尝试卸载重装也没用，MAC版本：10.13.6 软件版本：1.2.9

![qq20180803-232511](https://user-images.githubusercontent.com/14991024/43651301-904c316a-9774-11e8-87aa-81828a8bad1d.png)

**Comment by trazyn** [comment]
应该是这个问题 #239

**Comment by trazyn** [comment]
![screen shot 2018-08-04 at 4 23 12 am](https://user-images.githubusercontent.com/1774898/43664073-1f25f21c-979e-11e8-815b-577f32e664ac.png)
网络请求这里也截个图看看

**Comment by datou1996** [comment]
![qq20180804-074330](https://user-images.githubusercontent.com/14991024/43670003-1fd8b390-97ba-11e8-8e01-0c9ffad9cef4.png)

**Comment by trazyn** [comment]
![screen shot 2018-08-04 at 9 51 11 am](https://user-images.githubusercontent.com/1774898/43671401-f570cc3e-97cb-11e8-9e34-5062f0167fcf.png)

![screen shot 2018-08-04 at 9 50 06 am](https://user-images.githubusercontent.com/1774898/43671398-e0c6d6ac-97cb-11e8-9925-a69937e23fa8.png)


看看这个文件内容是不是正确的，不是的话直接删掉下面目录
```sh
rm -rf Library/Application\ Support/iease-music/
```

**Comment by datou1996** [comment]
里面是空的，执行完命令以后好了，感谢
![qq20180804-095926](https://user-images.githubusercontent.com/14991024/43671469-52b4d934-97cd-11e8-99d5-90697ef08e32.png)
