### ISSUE TITLE
微博登录不支持

### ISSUE THREAD

**Issue by NiftyMule** [trazyn/ieaseMusic#252]
希望加入其他登陆方式=。 =
一直在用微博帐号， 微信绑定了另一个帐号，也没有国内手机号绑定
用不了这软件就很难受=。 =
啥时候考虑一下加入其他第三方登录方式呗

**Comment by trazyn** [comment]
新浪的扫码登录太烂，一直系统繁忙

**Comment by ian-peng** [comment]
請問會加入微博帳號嗎？？

**Comment by trazyn** [comment]
等加完班下个版本加上
