### ISSUE TITLE
ubuntu 18.04 top panel icon not display

### ISSUE THREAD

**Issue by wisecsj** [trazyn/ieaseMusic#256]
ubuntu 18.04 
gnome 3.28

打开应用，顶部未出现托盘图标。已安装topicon。

**Comment by XiaoDianDi** [comment]
同18.04 有icon的。
顶部的icon是个黑色的和小汽车一样的，不在托盘里。
![-20180813234606-233x33](https://user-images.githubusercontent.com/10094017/44042542-1a8fb58c-9f53-11e8-9133-3960fc9a9125.png)

**Comment by wisecsj** [comment]
@XiaoDianDi 

我的是这样的，打开并没有..
![default](https://user-images.githubusercontent.com/10665384/44071152-17cc5960-9fba-11e8-9916-71ff71a1ab70.png)

PS：你的小飞机项目地址能分享下么 - -

**Comment by XiaoDianDi** [comment]
@wisecsj 
我觉得可能是你安装的gnome扩展问题
我用的topicon plus，不过topicon只是处理tray icon，ieaseMusic icon不在托盘里。 
https://extensions.gnome.org/extension/1031/topicons/
PS 小飞机是Telegram客户端
另一款小飞机：https://github.com/shadowsocks/shadowsocks-qt5

**Comment by wisecsj** [comment]
@XiaoDianDi  

扩展应该没问题，我打开你给的topicon连接，也是显示我已开启
![default](https://user-images.githubusercontent.com/10665384/44076398-ad126e34-9fd2-11e8-892f-5a0ce806c844.png)
ubuntu没用多久，没太理解“topicon只是处理tray icon，ieaseMusic icon不在托盘里”这句话。顶部的这些图标不是叫tray icon么？

PS：没认出来，我还以为是小飞机呢，hh

**Comment by wisecsj** [comment]
@XiaoDianDi 
懂了... 所以是ieaseMusic的icon本来就是显示在top panel的。但是由于我自己机子的环境或者什么问题，没有显示出来？

**Comment by XiaoDianDi** [comment]
@wisecsj 
是的
建议把扩展都关掉，看看是不是扩展影响。

**Comment by wisecsj** [comment]
@XiaoDianDi  刚试了下，我自己主动安装的也就一两个扩展。全都关掉了，还是未显示。

不过还是谢谢啦

**Comment by wisecsj** [comment]
应该是我自己的问题。
我的ubuntu appindicator 没有正常启用

![default](https://user-images.githubusercontent.com/10665384/44128147-e9627b4e-a073-11e8-9edd-e56eac725b4d.png)
