### ISSUE TITLE
相似歌手不显示

### ISSUE THREAD

**Issue by zhaowweny** [trazyn/ieaseMusic#259]
相似歌手部分没有内容，最新版本也没有。在开发者工具里面发现好像拿到的相似艺人是空的。

**Comment by zhaowweny** [comment]
@trazyn 刚刚打开正常了，之前一段时间连listening history都没有的，昨天看了都没有，刚刚打开居然有了😅

**Comment by trazyn** [comment]
有些没有版权的歌曲这些信息也是没有的
