### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by willhunger** [trazyn/ieaseMusic#26]
1. 隐藏Linux下的标题栏 
这样看着真的好丑，标题栏极度不协调

![image](https://user-images.githubusercontent.com/5282859/31014200-48648642-a54c-11e7-8b54-fa3b675eca87.png)

2. 增加QQmusic版本
 曲库全加上如此完美的设计，真的逆天
3. 加入last.fm记录
 lastfm官方有api，希望更加完美地记录听歌记录
4. 不要评论功能
 评论功能直接引导去官方页面吧 
4. 谢谢开发如此漂亮的播放器

**Comment by trazyn** [comment]
1. 这个在另外一个里面提到过，linux下borderless模式可交互元素需要设置`-webkit-app-region: no-drag`（在linux的electron才会这样），目前旅游没什么时间处理，所以只是简单加了title
2. 这个在#3里面有提到，翻了代码能拿到QQ的
3. 这个在 TODO 里面已经列出
4. 这个要做也是最后进行了，看情况吧
5. 谢谢反馈和夸奖

**Comment by wendingp** [comment]
不要评论+1, 播放器就专心听歌

**Comment by trazyn** [comment]
@wendingp 很奇怪为啥都不喜欢评论

**Comment by wendingp** [comment]
额, 因为虽然有些评论写的挺好的, 但是看多了就真心觉得没意思, 段子手太多

**Comment by trazyn** [comment]
All Done！
