### ISSUE TITLE
下载音乐完成之后文件自动消失

### ISSUE THREAD

**Issue by sackery** [trazyn/ieaseMusic#261]

**Comment by SeptemberHX** [comment]
最新版 1.3.0 有这个问题，上一个版本没有问题。

**Comment by trazyn** [comment]
看看本地的物理文件在不在，会同步本地文件，本地文件不在了就不会再显示了

**Comment by SeptemberHX** [comment]
文件确实下载了，没下完的时候在下载目录能看见该文件的。但是一旦下载完成后，文件就消失了。下载列表里的下载完成还有该项。

**Comment by trazyn** [comment]
我的正常😂，看看你的控制台有没错误输出，在下载窗口哪里按`option+cmd+I`
![screen shot 2018-08-20 at 10 04 15 am](https://user-images.githubusercontent.com/1774898/44316814-73b72c00-a460-11e8-8afa-ca7e50ddaeb8.png)

**Comment by sackery** [comment]
@trazyn 我用的是archlinux，下载的时候文件夹里还是存在文件的，完成后文件就自动删除了！

**Comment by SeptemberHX** [comment]
![image](https://user-images.githubusercontent.com/18042424/44339982-f918fb80-a4b5-11e8-936a-261615e6fd75.png)

报错如上。下载完成后，会报最后那个错误，然后文件消失。

**Comment by lorki** [comment]
> 我的正常😂，看看你的控制台有没错误输出，在下载窗口哪里按`option+cmd+I`
> ![screen shot 2018-08-20 at 10 04 15 am](https://user-images.githubusercontent.com/1774898/44316814-73b72c00-a460-11e8-8afa-ca7e50ddaeb8.png)

大锅的fish主题漂亮哇。给个分享呗。谢谢！

**Comment by trazyn** [comment]
主题是`hulk`字体是`Envy Code R for Powerline`
初始图案
```
cowsay -f dragon-and-cow "Greetings, Human!" | lolcat
```

**Comment by lorki** [comment]
> 主题是`hulk`字体是`Envy Code R for Powerline`
> 初始图案
> 
> ```
> cowsay -f dragon-and-cow "Greetings, Human!" | lolcat
> ```

谢谢大锅！
