### ISSUE TITLE
软件打开后，就不停地下一首下一首。

### ISSUE THREAD

**Issue by damye1** [trazyn/ieaseMusic#262]
打开软件后，就弹出下一首，点击next，瞬间有弹出下一首，一首歌都放不了

**Comment by Alalalalaki** [comment]
一样、、、、、、、

**Comment by trazyn** [comment]
控制台输出看看

**Comment by Alalalalaki** [comment]
@trazyn 不好意思不太了解控制台输出是怎么弄？ 还有可能没有描述清问题，具体问题是：

人在日本使用日本网代后，发现所有网易云音乐灰掉的歌都会读不出来，然后程序会自动不停地Up Next下一首，直到非灰的歌才会正常播放。终端测试 ping cdnetworks.com 在没用网代时正常，在用网代后全部parket loss。不过没用网代时几乎什么歌都不能正常播放。

另外在使用网代之后，微信的二维码登录无效了，二维码读不出来。如果不用网代可以登录，但是再改host之后又没登录了。

另外点下载之后没有发现相关文件夹有任何文件。

无论如何，感谢您的开发和分享。

**Comment by trazyn** [comment]
国外使用需要修改host或者代理进行unblock
