### ISSUE TITLE
启动的时候总是弹窗报错,和我的几个建议

### ISSUE THREAD

**Issue by ghost** [trazyn/ieaseMusic#267]
RT,一开始使用的版本为`1.1.5`,然后下载了1.3的`.deb`安装了,不过在启动中总是报错
![_ _20180821201426](https://user-images.githubusercontent.com/42143347/44400828-37c6b880-a57f-11e8-8c18-0b00c0f8c17d.png)
第二个报错，是不是代理问题导致的?我不怎么知道
![_ _20180821201541](https://user-images.githubusercontent.com/42143347/44400863-54fb8700-a57f-11e8-88f3-5b78c761e5ba.png)
一片空白
![_ _20180821201828](https://user-images.githubusercontent.com/42143347/44401301-cbe54f80-a580-11e8-9fd7-df7107644023.png)

前几次打开能用,发现UI大改,还是一如既往的cool,我习惯性的关闭窗口,进程就关闭了?
是bug还是现在版本就是窗口关闭了,主进程就干掉了呢
不明觉厉,我提几个个人小小的建议
![_ _20180821202352](https://user-images.githubusercontent.com/42143347/44401324-dc95c580-a580-11e8-9da0-73436c302e0a.png)

这里的话,还是建议能优化一下,还是和以前版本一样会不小心触碰到,然后hover进度条的时候也能优化一下,1.1.5的时候实在太鸡肋,太小了经常性的点错,给大大个建议,当hover进度条的时候,下方设置其不可click,最好也能加一层蒙版,或者直接设置其高度为下方播放条的高度,设置其颜色为rgba就毫无违和感这样的话操作起来就极好.还有就是如果真的就是窗口关闭就关了的话,还是建议如以前一样,关闭之后能保留进程.
![_ _20180821203658](https://user-images.githubusercontent.com/42143347/44401678-f97ec880-a581-11e8-8c70-d42c9696988d.png)

可以的话,能不能把本地音乐播放功能也搞起来,哈哈

再然后的话希望大大能够打包一下windows平台下的,

Thank you :kissing_heart:

**Comment by trazyn** [comment]
1. 截图的第一个错误是网络问题，会有高频调用限制，建议参照`README`进行`UNBLOCK`。
2. 关闭后主进程也会关闭，这个得看看你的桌面环境了，打包时候设置`executableName`然后由桌面环境管理的。
3. 没有本地音乐是由于很多歌曲相关数据没有，强行嵌进来有点别扭，最新的加入了下载功能，后面会增加播放已下载歌曲的功能
4. `Windows`不用`Windows`系统，所以就懒得适配了

**Comment by kmvan** [comment]
貌似启动要很久好久时间，是在监听文件吗？我home用户目录下文件比较多，会造成影响吗？还没看源码，猜测一下。

**Comment by amitbha** [comment]
是哦，启动很慢，大概20s，界面在等网络吗？

**Comment by trazyn** [comment]
打开的时候会请求`login/refresh`更新`Cookie`，请求完毕结束白屏，加载 UI
加载 UI 时候会请求多个接口分别拿到日推红心歌曲，其他推荐歌曲
看看是哪个阶段加载慢了（我是用自己服务器进行的 Unblock）
![screen shot 2018-09-18 at 11 52 23 am](https://user-images.githubusercontent.com/1774898/45663506-66fa2680-bb39-11e8-8395-e8826897db5a.png)

**Comment by trazyn** [comment]
Close https://github.com/trazyn/ieaseMusic/commit/95e4fff5cd8678d330761a2ccb5ac6c4d469d310
