### ISSUE TITLE
有一部分歌只播放伴奏

### ISSUE THREAD

**Issue by ymmshi** [trazyn/ieaseMusic#268]
1. 在网易云收藏的部分歌播放时都是播放伴奏.
2. 由于网络原因经常会有弹窗跳出,这样对于用户是不友好的,能否将这些弹窗去除.

**Comment by trazyn** [comment]
1. 参考 #243 
2. 参考 `README UNBLOCK`

**Comment by ymmshi** [comment]
谢谢你的解答!
1.就是酷狗音乐的问题,屏蔽酷狗就好了
2.由于我个人工作原因,经常需要翻墙,有时候就会跳出弹窗,不知道能否设置自己选择代理

**Comment by trazyn** [comment]
自己有服务器的话可以开个`nginx`做反代，`real-ip`设置成网易的，基本不会跳高频访问限制，我就是这么用的
