### ISSUE TITLE
V 1.3.0 版本的 Ubuntu1804 下载音乐不断弹出正在下载音乐的提示

### ISSUE THREAD

**Issue by AbaoFromCUG** [trazyn/ieaseMusic#272]
![image](https://user-images.githubusercontent.com/24972096/44636701-cc963f80-a9df-11e8-9869-d61d9b4c502d.png)

如上，我右键歌曲，点击download 后不断的弹出正在下载的提示

**Comment by trazyn** [comment]
Fix [2e3795b7](https://github.com/trazyn/ieaseMusic/commit/2e3795b77b28c994b1410dc3f4dbfd29dcfa1b3c)
