### ISSUE TITLE
只能搜索歌单而不能搜索特定的歌曲吗？

### ISSUE THREAD

**Issue by lgsen1996** [trazyn/ieaseMusic#278]
我的系统是Ubuntu16.04，用的是AppImage版本，我搜索歌曲的时候只能搜索歌单，想找某一首歌曲只能搜歌手然后在专辑里面找。大家是怎么搜知道歌名的歌曲的？还是说暂时不支持？谢谢！

**Comment by ZhengshuaiPENG** [comment]
+1 好像没有直接歌曲的排序结果

**Comment by trazyn** [comment]
搜歌曲出来的是歌单，点开对应歌单或专辑
