### ISSUE TITLE
是否将timeline上面的时间黑框默认隐藏会好点？

### ISSUE THREAD

**Issue by lorki** [trazyn/ieaseMusic#279]
是否将timeline上面的时间黑框默认隐藏会好点？鼠标移动到timeline再显示出来，用户体验也许会更好。

**Comment by lorki** [comment]
QQ音乐的api出现问题了

**Comment by lorki** [comment]
另外如果歌单背景是白色的，菜单按钮会看不见。

**Comment by trazyn** [comment]
试了下，QQ 的 API 正常啊

**Comment by lorki** [comment]
哈哈哈，我没有用代理。用了一个转链api完成了qq音乐死链的问题。

建议海外用户用下面这个QQ.js代码：

`

import _debug from 'debug';
import chalk from 'chalk';

const debug = _debug('dev:plugin:QQ');
const error = _debug('dev:plugin:QQ:error');

let rp;

async function getSong(mid) {
    return {
        bitRate: 320000,
        src: getURL(`${mid}.mp3`),
    };
}

function getURL(filename) {
    return `http://link.hhtjim.com/qq/${filename}`;
}

export default async(request, keyword, artists) => {
    debug(chalk.black.bgGreen('💊  Loaded QQ music.'));

    rp = request;

    try {
        var response = await rp({
            uri: 'http://c.y.qq.com/soso/fcgi-bin/search_cp',
            qs: {
                w: [keyword].concat(artists.split(',')).join('+'),
                p: 1,
                n: 100,
                aggr: 1,
                lossless: 1,
                cr: 1,
                format: 'json',
                inCharset: 'utf8',
                outCharset: 'utf-8',
            },
        });

        var data = response.data;

        if (response.code !== 0
            || data.song.list.length === 0) {
            error(chalk.black.bgRed('🚧 List Nothing.'));
            return Promise.reject(Error(404));
        }

        for (let e of data.song.list) {
            let song = {};

            // Match the artists
            if (e.singer.find(e => artists.indexOf(e.name) === -1)) {
                continue;
            }

            song = await getSong(e.media_mid);

            if (!song.src) {
                error(chalk.black.bgRed('🚧 Song Nothing.'));
                return Promise.reject(Error(404));
            }

            debug(chalk.black.bgGreen('🚚  Result >>>'));
            debug(e);
            debug(chalk.black.bgGreen('🚚  <<<'));

            return song;
        }
    } catch (ex) {
        error('Failed to get song: %O', ex);
        return Promise.reject(ex);
    }

    error(chalk.black.bgRed('🈚  Not Matched.'));
    return Promise.reject(Error(405));
};

`

**Comment by trazyn** [comment]
我试试
