### ISSUE TITLE
显示进程错误，进不去

### ISSUE THREAD

**Issue by hong1002** [trazyn/ieaseMusic#282]
弹框提示：
A JavaScript error occurred in the main process

Uncaught Exception:
Error: read ECONNRESET
at _errorException(util.js: 1024: 11)
at TCP.onread(net.js: 615: 25)

**Comment by DraculaPrince** [comment]
同错误

**Comment by trazyn** [comment]
官方 API 高频限制，参考 `Unblock`

**Comment by trazyn** [comment]
Close https://github.com/trazyn/ieaseMusic/commit/95e4fff5cd8678d330761a2ccb5ac6c4d469d310
