### ISSUE TITLE
怎么同步last.fm

### ISSUE THREAD

**Issue by martinsol** [trazyn/ieaseMusic#283]
看了一圈没找到
----------------------------------------------------------------------------------------------------------------------------------------------找到了，藏的有点深

**Comment by trazyn** [comment]
设置里面登录 lasfm
![screen shot 2018-09-17 at 4 28 41 pm](https://user-images.githubusercontent.com/1774898/45612808-c3583a00-ba96-11e8-85b9-e3d18e941edd.png)

**Comment by uptonking** [comment]
我找了好久都没找到。。。

**Comment by uptonking** [comment]
终于找到了，在任何地方右键可以出现好多菜单，，，
返回键在Ubuntu上是个白色的点，看不清
