### ISSUE TITLE
不能通过邮箱登入只能手机号？

### ISSUE THREAD

**Issue by frankiezdh** [trazyn/ieaseMusic#284]

**Comment by trazyn** [comment]
受接口限制 目前是没有邮箱登录的，只能手机登录微信登录

**Comment by sssir** [comment]
这个接口失效了吗？
https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=_2-%E9%82%AE%E7%AE%B1%E7%99%BB%E5%BD%95

**Comment by trazyn** [comment]
找个接口要验证码
