### ISSUE TITLE
每次打开app都会有联网提示，1.3.1版本，macOS 10.13.1

### ISSUE THREAD

**Issue by char1eslu** [trazyn/ieaseMusic#290]
![image](https://user-images.githubusercontent.com/20885743/45915164-f9286480-be82-11e8-8706-312bbcd1f6d0.png)

**Comment by trazyn** [comment]
osx 10.12.6 没有出现这个，在`Security & Privacy preferences`里面不能设置？

**Comment by char1eslu** [comment]
> osx 10.12.6 没有出现这个，在`Security & Privacy preferences`里面不能设置？
设置为允许了，每次还是出现，怀疑是系统的锅。。。

**Comment by char1eslu** [comment]
顺便问下，resource里面的dock.icns 是封装起来了嘛，没找到。。。

**Comment by trazyn** [comment]
![screen shot 2018-09-22 at 5 02 13 pm](https://user-images.githubusercontent.com/1774898/45915553-43acdf80-be89-11e8-9208-ea1f4fdd9c86.png)

**Comment by char1eslu** [comment]
嗯，我发现替换个图标后，当程序未运行时，Dock和Launchpad都是显示我替换的图标，但是程序运行后，Dock的图标又变成之前的了

**Comment by trazyn** [comment]
仅改变dock栏的可能改不了 全在asar里面

**Comment by char1eslu** [comment]
这样啊，好吧，谢谢啦，感谢回答我这么多问题！
