### ISSUE TITLE
大部分歌曲都不能播放了，啥情况

### ISSUE THREAD

**Issue by daniel123c** [trazyn/ieaseMusic#291]
![-20180924142607-769x298](https://user-images.githubusercontent.com/42375432/45939525-d1add500-c005-11e8-9fa5-297a26b0b5af.png)

**Comment by huiyifyj** [comment]
另选代理节点试试吧。你这个代理IP估计不稳定。

**Comment by daniel123c** [comment]
是那个你的日本ip🤔🤔

Huiyi.FYJ <notifications@github.com> 于 2018年9月25日周二 下午1:18写道：

**Comment by trazyn** [comment]
![screen shot 2018-09-27 at 11 10 14 am](https://user-images.githubusercontent.com/1774898/46121351-f8f2e500-c245-11e8-8de8-c421475f76b0.png)
正常

**Comment by trazyn** [comment]
Update apis https://github.com/trazyn/ieaseMusic/commit/95e4fff5cd8678d330761a2ccb5ac6c4d469d310
