### ISSUE TITLE
Cause netease cloud music memory leak

### ISSUE THREAD

**Issue by grauspitz** [trazyn/ieaseMusic#302]
When I installed this software, there was a serious memory leak in the netease cloud that could not be fixed. The original script failed in 2016, and the uninstall and reload was not effective, manjaro-dde

**Comment by trazyn** [comment]
嗯发现了，确实有个内存泄漏的问题，挂了 UNBLOCK 后网易的`subscribe`接口会一直挂起，然后内存泄漏

**Comment by grauspitz** [comment]
居然反应这么快，所以这是你的最终目的？我现在网易云完全没法用，不一会就占满16g内存然后系统卡死，有什么解决办法吗

**Comment by grauspitz** [comment]
不好意思语气严重了，不过谢谢回复，希望尽快给个解决办法

**Comment by trazyn** [comment]
关闭subscribe to neteasemusic 在设置里面有的

**Comment by grauspitz** [comment]
没起作用...先用你这个吧，希望越来越好

**Comment by trazyn** [comment]
Update https://github.com/trazyn/ieaseMusic/commit/95e4fff5cd8678d330761a2ccb5ac6c4d469d310
