### ISSUE TITLE
频繁弹出JavaScript错误

### ISSUE THREAD

**Issue by ShaunZh** [trazyn/ieaseMusic#314]
![image](https://user-images.githubusercontent.com/12807720/47418431-ac4eeb00-d7ac-11e8-9a17-64189bc84f03.png)

**Comment by chienhao10** [comment]
同上有时候跳出不止8个窗口。还好touch bar可以快速点击‘好’ 😊
借个帖子汇报另一个，讲视窗最小化后貌似就不能下一首歌了，除非不要点击最小化，就将其放在桌面的最底层。

**Comment by unreal0** [comment]
tcp断线问题,已经部分解决
