### ISSUE TITLE
国产音乐播放器为啥菜单是英文呢？

### ISSUE THREAD

**Issue by AskSky924** [trazyn/ieaseMusic#315]

**Comment by Superzero31** [comment]
By this way u could learn English.

**Comment by chienhao10** [comment]
I have no problem with all this in English. 🙃
and I like it in English, maybe its same with the dev.

**Comment by Lxjazni7** [comment]
因为很多UI改成中文了会没有英文好看🤣🤣

**Comment by Sean1256** [comment]
no very difficult word, and the author may like use English in coding like me.
