### ISSUE TITLE
听歌时长是否会算进网易云音乐统计

### ISSUE THREAD

**Issue by MuYunyun** [trazyn/ieaseMusic#320]
如果使用这个 app 听音乐，听歌时长会算进网易云音乐的统计么？因为网易云音乐等级是靠听歌时长加上去的。如果不行的话有没有相应的 hack 手段:smile:

**Comment by trazyn** [comment]
音乐统计调用`subscribe`接口（https://github.com/trazyn/ieaseMusic/blob/master/server/api/subscribe.js），可以自己随意刷统计数据
