### ISSUE TITLE
ERROR in ./server/api.js

### ISSUE THREAD

**Issue by Giagoo** [trazyn/ieaseMusic#321]
Windows10

ERROR in ./server/api/sub.js
Module not found: Error: Can't resolve '../../NeteaseCloudMusicApi/util/util' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server\api'
 @ ./server/api/sub.js 6:15-62
 @ ./server/api.js
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api/thumbsup.js
Module not found: Error: Can't resolve '../../NeteaseCloudMusicApi/util/util' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server\api'
 @ ./server/api/thumbsup.js 6:15-62
 @ ./server/api.js
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api/subscribe.js
Module not found: Error: Can't resolve '../../NeteaseCloudMusicApi/util/util' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server\api'
 @ ./server/api/subscribe.js 6:15-62
 @ ./server/api.js
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api/unsubscribe.js
Module not found: Error: Can't resolve '../../NeteaseCloudMusicApi/util/util' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server\api'
 @ ./server/api/unsubscribe.js 6:15-62
 @ ./server/api.js
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api/follow.js
Module not found: Error: Can't resolve '../../NeteaseCloudMusicApi/util/util' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server\api'
 @ ./server/api/follow.js 6:15-62
 @ ./server/api.js
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api/unfollow.js
Module not found: Error: Can't resolve '../../NeteaseCloudMusicApi/util/util' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server\api'
 @ ./server/api/unfollow.js 6:15-62
 @ ./server/api.js
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api/hot_album.js
Module not found: Error: Can't resolve '../../NeteaseCloudMusicApi/util/util' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server\api'
 @ ./server/api/hot_album.js 6:15-62
 @ ./server/api.js
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api/unsub.js
Module not found: Error: Can't resolve '../../NeteaseCloudMusicApi/util/util' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server\api'
 @ ./server/api/unsub.js 6:15-62
 @ ./server/api.js
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api/login_refresh.js
Module not found: Error: Can't resolve '../../NeteaseCloudMusicApi/util/util' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server\api'
 @ ./server/api/login_refresh.js 6:15-62
 @ ./server/api.js
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api/loginCellphone.js
Module not found: Error: Can't resolve '../../NeteaseCloudMusicApi/util/util' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server\api'
 @ ./server/api/loginCellphone.js 7:15-62
 @ ./server/api.js
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api/login.js
Module not found: Error: Can't resolve '../../NeteaseCloudMusicApi/util/util' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server\api'
 @ ./server/api/login.js 7:15-62
 @ ./server/api.js
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api/scrobble.js
Module not found: Error: Can't resolve '../../NeteaseCloudMusicApi/util/util' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server\api'
 @ ./server/api/scrobble.js 6:15-62
 @ ./server/api.js
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/album' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 46:18-65
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/artist_album' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 52:25-79
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/artists' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 49:20-69
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/artists_desc' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 55:24-78
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/artists_mv' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 58:22-74
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/banner' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 61:19-67
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/check_music' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 63:24-77
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/comment_album' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 69:26-81
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/comment_dj' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 73:23-75
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/comment_music' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 65:26-81
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/comment_mv' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 67:23-75
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/comment_playlist' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 71:29-87
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/daily_signin' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 76:25-79
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/dj_catelist' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 88:24-77
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/dj_detail' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 79:22-73
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/dj_hot' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 90:19-67
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/dj_program' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 82:23-75
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/dj_program_detail' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 84:30-89
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/dj_recommend' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 93:25-79
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/dj_recommend_type' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 96:30-89
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/dj_sub' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 86:19-67
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/event' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 99:18-65
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/fm_trash' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 102:21-71
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/like' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 105:17-63
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/likelist' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 107:21-71
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/logWeb' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 110:20-68
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/lyric' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 113:18-65
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/musicUrl' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 116:22-72
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/mv' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 125:15-59
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/mv_first' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 119:21-71
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/mv_url' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 122:19-67
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/personal_fm' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 128:24-77
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/personalized' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 131:62-116
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/personalized_djprogram' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 134:35-99
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/personalized_mv' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 143:28-85
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/personalized_newsong' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 137:33-95
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/personalized_privatecontent' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 140:40-109
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/playlist_catlist' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 153:29-87
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/playlist_detail' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 146:28-85
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/playlist_hot' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 151:25-79
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/playlist_tracks' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 149:28-85
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/program_recommend' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 156:30-89
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/recommend_dislike' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 165:30-89
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/recommend_resource' in'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 162:68-128
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/recommend_songs' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 159:65-122
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/resource_like' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 167:26-81
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/search' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 170:19-67
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/search_multimatch' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 173:30-89
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/search_suggest' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 176:27-83
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/simi_artists' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 191:24-78
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/simi_mv' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 185:20-69
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/simi_playlist' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 179:26-81
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/simi_song' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 182:22-73
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/simi_user' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 188:22-73
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/song_detail' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 194:24-77
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/top_album' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 197:22-73
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/top_artists' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 200:24-77
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/top_list' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 202:21-71
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/top_mv' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 204:19-67
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/top_playlist' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 207:25-79
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/top_playlist_highquality' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 210:37-103
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/top_songs' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 212:21-72
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/toplist' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 214:20-69
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/toplist_artist' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 216:27-83
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/toplist_detail' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 218:27-83
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/user_audio' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 224:23-75
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/user_cloud' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 227:23-75
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/user_cloud_search' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 230:30-89
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/user_detail' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 235:24-77
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/user_dj' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 237:20-69
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/user_event' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 233:23-75
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/user_followeds' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 239:27-83
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/user_follows' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 241:25-79
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/user_playlist' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 221:26-81
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/user_playrecord' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 245:24-81
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/user_subcount' in 'C:\Users\JIAHAOCHEN\Documents\ieaseMusic\server'
 @ ./server/api.js 243:26-81
 @ ./main.js
 @ multi babel-polyfill ./main.js
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! iease-music@1.3.1 build-main: `cross-env NODE_ENV=production node -r babel-register ./node_modules/webpack/bin/webpack --config ./config/webpack.config.electron.js --progress --profile --colors`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the iease-music@1.3.1 build-main script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\JIAHAOCHEN\AppData\Roaming\npm-cache\_logs\2018-10-29T14_02_20_025Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! iease-music@1.3.1 build: `npm run build-main && npm run build-renderer`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the iease-music@1.3.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\JIAHAOCHEN\AppData\Roaming\npm-cache\_logs\2018-10-29T14_02_20_149Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! iease-music@1.3.1 package-win: `npm run build && rm -rf release && build --win --ia32 --projectDir ./dist`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the iease-music@1.3.1 package-win script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\JIAHAOCHEN\AppData\Roaming\npm-cache\_logs\2018-10-29T14_02_20_212Z-debug.log

Log :
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'package-win' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose run-script [ 'prepackage-win', 'package-win', 'postpackage-win' ]
5 info lifecycle iease-music@1.3.1~prepackage-win: iease-music@1.3.1
6 info lifecycle iease-music@1.3.1~package-win: iease-music@1.3.1
7 verbose lifecycle iease-music@1.3.1~package-win: unsafe-perm in lifecycle true
8 verbose lifecycle iease-music@1.3.1~package-win: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\JIAHAOCHEN\Documents\ieaseMusic\node_modules\.bin;C:\Users\JIAHAOCHEN\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\JIAHAOCHEN\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Git\cmd;C:\Program Files\nodejs;C:\Users\JIAHAOCHEN\AppData\Local\Microsoft\WindowsApps;C:\Users\JIAHAOCHEN\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\JIAHAOCHEN\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle iease-music@1.3.1~package-win: CWD: C:\Users\JIAHAOCHEN\Documents\ieaseMusic
10 silly lifecycle iease-music@1.3.1~package-win: Args: [ '/d /s /c',
10 silly lifecycle   'npm run build && rm -rf release && build --win --ia32 --projectDir ./dist' ]
11 silly lifecycle iease-music@1.3.1~package-win: Returned: code: 2  signal: null
12 info lifecycle iease-music@1.3.1~package-win: Failed to exec package-win script
13 verbose stack Error: iease-music@1.3.1 package-win: `npm run build && rm -rf release && build --win --ia32 --projectDir ./dist`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid iease-music@1.3.1
15 verbose cwd C:\Users\JIAHAOCHEN\Documents\ieaseMusic
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "package-win"
18 verbose node v8.12.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 2
22 error iease-music@1.3.1 package-win: `npm run build && rm -rf release && build --win --ia32 --projectDir ./dist`
22 error Exit status 2
23 error Failed at the iease-music@1.3.1 package-win script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

**Comment by trazyn** [comment]
```
git submodule init
git submodule update
```

**Comment by trazyn** [comment]
在工程的根目录下面

**Comment by Giagoo** [comment]
> 在工程的根目录下面

我是在根目录下试的，不行
$ git submodule update
fatal: destination path 'C:/Users/JIAHAOCHEN/Documents/ieaseMusic/NeteaseCloudMusicApi' already exists and is not an empty directory.
fatal: clone of 'https://github.com/trazyn/NeteaseCloudMusicApi' into submodule path 'C:/Users/JIAHAOCHEN/Documents/ieaseMusic/NeteaseCloudMusicApi' failed
Failed to clone 'NeteaseCloudMusicApi'. Retry scheduled
fatal: destination path 'C:/Users/JIAHAOCHEN/Documents/ieaseMusic/NeteaseCloudMusicApi' already exists and is not an empty directory.
fatal: clone of 'https://github.com/trazyn/NeteaseCloudMusicApi' into submodule path 'C:/Users/JIAHAOCHEN/Documents/ieaseMusic/NeteaseCloudMusicApi' failed
Failed to clone 'NeteaseCloudMusicApi' a second time, aborting

这是运行update的反馈

**Comment by Giagoo** [comment]
我重新安装API试试

**Comment by trazyn** [comment]
```
rm -rf NeteaseCloudMusicApi
git submodule init
git submodule update
```

**Comment by Giagoo** [comment]
> ```
> rm -rf NeteaseCloudMusicApi
> git submodule init
> git submodule update
> ```

成功了！谢谢大神
