### ISSUE TITLE
项目代码运行环境问题

### ISSUE THREAD

**Issue by kscarrot** [trazyn/ieaseMusic#322]
config/webpack.config在导入模块的时候直接用到了import,看着很舒适.
请问作者在开发过程中node的运行环境是直接用高版本然后开启了import的功能吗?

**Comment by trazyn** [comment]
并没有高版本 
[https://babeljs.io/docs/en/babel-register](https://babeljs.io/docs/en/babel-register)

**Comment by kscarrot** [comment]
明白了,多谢
