### ISSUE TITLE
右上角的星星是收藏歌单的功能么，按按没有反应……

### ISSUE THREAD

**Issue by GTGraphics3** [trazyn/ieaseMusic#327]
<img width="258" alt="image" src="https://user-images.githubusercontent.com/44542198/47982756-e0f76680-e10b-11e8-97fa-3b871ce53da8.png">

**Comment by trazyn** [comment]
Close https://github.com/trazyn/ieaseMusic/commit/95e4fff5cd8678d330761a2ccb5ac6c4d469d310
