### ISSUE TITLE
建议增加针对~/.config/iease-music/Cache/下的缓存文件上限控制策略

### ISSUE THREAD

**Issue by StandAlong** [trazyn/ieaseMusic#334]
在使用该软件播放音乐后，~/.config/iease-music/Cache/目录下的图片、歌曲缓存占用空间大小会急速增加，不知道软件内是否有针对缓存目录的大小控制策略。在.config目录下写入大量缓存不符合Linux使用规范。建议将程序产生的缓存数据传入数据库，将歌曲缓存数据在其他位置创建缓存目录，然后加入空间限制策略，否则会造成Linux home目录高度臃肿。

**Comment by trazyn** [comment]
这个应该得给Electron提issue
