### ISSUE TITLE
网易已经下架的歌曲是怎么做到能播放的

### ISSUE THREAD

**Issue by zhaominso** [trazyn/ieaseMusic#336]
最开心的应该就是能播放下架歌曲了，一瞬间周杰伦、林宥嘉都可以听了。有大佬能解释下这个是怎么做到的吗？直接请求网易云的API能返回下架歌曲？还是对于下架歌曲去请求的别的网站，比如ＱＱ音乐和虾米（自己之前就是想这么做的）？

**Comment by b-z** [comment]
同好奇。。以及这个真的没有版权问题吗。。

**Comment by jamesdongdong** [comment]
猜测是有很多账号然后搜索出来的。可能是大佬自费支持这些账号

**Comment by Robot-L** [comment]
因为不止网易的曲库啊 😏😏
![image](https://user-images.githubusercontent.com/16471200/50065247-86fcbd00-01f0-11e9-9099-a862db2c4092.png)

**Comment by zhaominso** [comment]
> 因为不止网易的曲库啊 
> ![image](https://user-images.githubusercontent.com/16471200/50065247-86fcbd00-01f0-11e9-9099-a862db2c4092.png)

这个是在哪的设置呀，我找了半天愣是没有找到

**Comment by Robot-L** [comment]
设置里面，往下翻就有啊。
