### ISSUE TITLE
%&%^*%$*@#$^%&^$%^#%^

### ISSUE THREAD

**Issue by leewi9** [trazyn/ieaseMusic#34]
![image](https://user-images.githubusercontent.com/10832544/31338334-5fdadb4e-acc4-11e7-90b6-46beb7946a19.png)

**Comment by trazyn** [comment]
参考 #20 要改下hosts

**Comment by feivorid** [comment]
@trazyn   修改完了  host 之后还是不好使   我在国内   mac端的      还是一直 please wait ....

**Comment by trazyn** [comment]
```
ping music.163.com
```
看看是否修改生效
![screen shot 2017-10-10 at 1 41 57 pm](https://user-images.githubusercontent.com/1774898/31370907-cd474e4a-adc0-11e7-867d-9cf43a90b76e.png)
