### ISSUE TITLE
歌曲名字与实际播放的不一致

### ISSUE THREAD

**Issue by char1eslu** [trazyn/ieaseMusic#340]
歌曲名字，艺人，专辑，时长都确定了，但是这个客户端和 原版的播放的却不是同一首歌，很奇怪。。。我是在我喜欢的列表里面播放的，两个客户端播放出来的不一样

**Comment by RamblerW** [comment]
+1

**Comment by cyh1123** [comment]
+1

**Comment by updater1234** [comment]
+1

**Comment by trazyn** [comment]
Close https://github.com/trazyn/ieaseMusic/issues/243
