### ISSUE TITLE
退回到上一个界面到功能可以做么。 

### ISSUE THREAD

**Issue by ZizaiCode** [trazyn/ieaseMusic#347]
比如说，点错之后，进入新的界面。 是否有方案退回到上一个界面。 比如说手势操作之类的

**Comment by Robot-L** [comment]
emmmmmm，左上角第4个按钮就是返回键，我也是用了半年才知道 : )

**Comment by yorushika** [comment]
想提一个类似的，比如从自己喜欢的歌单列表中进入一个歌单，然后点第四个返回，歌单列表就会回到开头，这对于长歌单翻阅非常不方便，有一个记忆功能就好了。

**Comment by trazyn** [comment]
@yorushika 退回的是上一个页面，A歌单进入B歌单，B歌单返回会回到A歌单
