### ISSUE TITLE
有些歌对不上

### ISSUE THREAD

**Issue by MetaphysicianLeo** [trazyn/ieaseMusic#348]
Paintёr
![image](https://user-images.githubusercontent.com/33951689/49426213-e6170680-f7da-11e8-8ac7-3768bf2687fb.png)
这首歌放出来实际上是
![image](https://user-images.githubusercontent.com/33951689/49426585-f8457480-f7db-11e8-9862-04927b5d2bc6.png)

**Comment by ZCY01** [comment]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/15939669/49718777-11e03380-fc96-11e8-9740-bc3480fa0765.png">
播放《渐渐》，但是实际上放的是《好久不见》
unblock 158.199.142.239 music.163.com interface.music.163.com p1.music.126.net p2.music.126.net p3.music.126.net p4.music.126.net

**Comment by trazyn** [comment]
https://github.com/trazyn/ieaseMusic/issues/243
