### ISSUE TITLE
一些建议,大佬可以瞅瞅

### ISSUE THREAD

**Issue by crper** [trazyn/ieaseMusic#37]
1. 提供`brew cask` 的安装方式
2. 希望聚合全网的在线音乐,比如QQ 的音乐库也能搜索!!! QQ+网易+虾米 ,我感觉基本90%的版权歌曲都能搜索到 
3. 提供`touchbar`的按钮
4. 提供比较完善的开发文档,方便其他小伙伴参与提交`PR`完善

**Comment by trazyn** [comment]
1. 周末给那边提交个pr吧
2. TODO里面些了高音质以及死链的问题
3. 手上没有touchbar的设备，有空找个看看吧
4. 我太懒了，这个也确实是个问题，后面我会试着去写一起文档

谢谢你的建议

**Comment by ryh** [comment]
Xcode 里有touchbar 模拟器
没有文档，来个roadmap也好（项目的预期方向）

**Comment by Gegoiuty** [comment]
求更新。

https://github.com/caskroom/homebrew-cask/blob/548808deb9e2f055928f4c7b0aac087b38942522/Casks/ieasemusic.rb

`==> Satisfying dependencies
==> Downloading https://github.com/trazyn/ieaseMusic/releases/download/v1.0.0/ieaseMusic-1.0.0-mac.d
######################################################################## 100.0%
==> Verifying checksum for Cask ieasemusic
==> Note: running "brew update" may fix sha256 checksum errors
Error: Checksum for Cask 'ieasemusic' does not match.

Expected: 1f9aba95c46499568e967d1975f974f66bfb46789cf4a4d88a11f5218e5c4662
Actual:   13178c0f70cabbfada0b4ee931fb729f50f4f0f8bdac602ce0cbbc73c4093ae3
File:     /Users/xiaoke/Library/Caches/Homebrew/Cask/ieasemusic--1.0.0.dmg

To retry an incomplete download, remove the file above.
`

**Comment by trazyn** [comment]
额 上次傻逼了，直接改了release的dmg，没更新sha256，差点都忘记了

**Comment by trazyn** [comment]
1. home brew已增加
亮度键旁边的展开按钮点击里面就有上一曲下一曲啊
