### ISSUE TITLE
After pull latest code, a error happend in dev:main

### ISSUE THREAD

**Issue by hdmy** [trazyn/ieaseMusic#385]
![image](https://user-images.githubusercontent.com/20206052/52609441-4bad0080-2eb8-11e9-9b67-d4cb15a73dee.png)
I want to pull its submodlue 'NesteaseCloudMusicApi', but it's always wrong.
![image](https://user-images.githubusercontent.com/20206052/52609455-58315900-2eb8-11e9-8c1c-5690e50e66d9.png)

**Comment by hdmy** [comment]
use `git submodule update` also wrong ⚠️
![image](https://user-images.githubusercontent.com/20206052/52699524-e38e1580-2fb0-11e9-964c-5cda98888467.png)

**Comment by trazyn** [comment]
Already fixed
