### ISSUE TITLE
mac一直转方块，使用的是release版本

### ISSUE THREAD

**Issue by maxwellxxx** [trazyn/ieaseMusic#386]
OS：mac 10.14.3 
software version：release 1.3.2-1.3.4 
![image](https://user-images.githubusercontent.com/6694798/52931620-f83f2480-3387-11e9-8fbf-fac5a215def2.png)

**Comment by xixuyishi** [comment]
同样的问题

**Comment by xixuyishi** [comment]
我的解决了。希望能帮到你
1.关闭系统代理
2.取消hosts文件有关网易云音乐的设置
3.重启ieaseMusic
