### ISSUE TITLE
electron 的问题

### ISSUE THREAD

**Issue by GTGraphics3** [trazyn/ieaseMusic#395]
已经安装了最新的electron
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/44542198/54065140-201efb00-4257-11e9-9ede-eb3ee57fb7bc.png">
但是系统控制播放的问题还是没有解决
是还有什么步骤没有做么

**Comment by GTGraphics3** [comment]
想让touch bar支持控制iease，系统是10.14

**Comment by luogreen** [comment]
Duplicate of #351

**Comment by GTGraphics3** [comment]
谢谢可以了😊
