### ISSUE TITLE
要求的node版本也太旧了吧

### ISSUE THREAD

**Issue by loveward** [trazyn/ieaseMusic#399]
jss@3.11.1: The engine "node" is incompatible with this module. Expected version ">=4.0.0 <6.0.0". Got "10.15.0"

**Comment by loveward** [comment]
解决了
使用yarn就会出现问题

使用 npm i 就不会有问题

**Comment by daihy8759** [comment]
我一般都是自己加环境变量：`alias yarn='yarn --ignore-engines'`

**Comment by ic-timon** [comment]
建议升10
