### ISSUE TITLE
关于海外党解锁

### ISSUE THREAD

**Issue by 0x5e** [trazyn/ieaseMusic#4]
我觉得只要代理music.163.com就可以了吧，如果代理了*.music.126.net然后代理服务器本身网络不好的话，听歌一卡一卡的完全就没法听了

**Comment by trazyn** [comment]
海外我就不知道了，国内到是还好的😂
你肉身在外不代理*.music.126.net会很流畅么？

**Comment by 0x5e** [comment]
嗯，挺流畅。。。我在英国，不过这个每个地方估计不一样

**Comment by trazyn** [comment]
谢谢反馈，我会写到 readme 里面的

**Comment by ITJesse** [comment]
这个还是跟网络环境相关。
目前看来的话，网易的 CDN 是没有任何海外优化的。
所以视各家运营商对入境线路的优化情况不同有很大差异。

**Comment by zhouhounan** [comment]
不会提示海外版权无法播放？

**Comment by trazyn** [comment]
@zhouhounan 改了hosts就不会了，无版权的会查其他第三方库（百度音乐，QQ音乐，酷狗音乐）

**Comment by TifosiRay** [comment]
@trazyn 请问要怎么代理百度音乐，QQ音乐，酷狗音乐
网易云的已经在host里添加了 但是不知道另外三个的地址

**Comment by trazyn** [comment]
@TifosiRay 另外三个在海外也不能访问么？

**Comment by TifosiRay** [comment]
@trazyn 是的，那三个也被限制了
今天还发现一个问题。 host改好后，原本那些因为ip被限制的歌 不会出现infinite notification loop了 但是等了很久也不能播放。同样的歌曲用网易云音乐的客户端就可以播放。 不知道是不是我设置出错了

**Comment by 0x5e** [comment]
@TifosiRay 能提供下这三个播放器，被限制的歌的播放链接吗？有空我可以帮你看下

刚才刚好有同学发了我酷我音乐的一首歌，版权问题听不了，然后也是找到host加了以后就ok了，所以我觉得我们是不是可以维护这么一份“绕过版权限制”的host列表：）

**Comment by michele1162** [comment]
坐标意大利，hosts改了依然不能正常播放歌曲。

**Comment by laserroger** [comment]
坐标美东，改hosts无效，不改hosts就无限提示&切歌

**Comment by felizdonny** [comment]
坐标美帝
改了hosts后就奏效了一首歌，然后就不能正常播放了，好无奈。。

**Comment by laserroger** [comment]
测试到目前为止唯一靠谱的办法是改dns，靠谱的dns：
45.32.72.192

**Comment by felizdonny** [comment]
@laserroger 我把Unblock youku的三个dns都试了一遍，依然不行

**Comment by yanjingzhaisun** [comment]
同修改 dns，并不能使用；网易云音乐客户端则可以播放无问题。

**Comment by trazyn** [comment]
现在支持多个曲库在国外使用除了私人电台还有日推基本没有不能播放问题
