### ISSUE TITLE
Linux Error

### ISSUE THREAD

**Issue by FFlowerS** [trazyn/ieaseMusic#40]
![snipaste_2017-10-17_21-19-01](https://user-images.githubusercontent.com/8475161/31667203-4f6c6a98-b381-11e7-958a-f7491fe6d244.png)

虽然确实说没有适配Linux啦，先给大佬一个图看看是啥问题好了

（10086端口是我的socks代理端口，剩下看不懂x）

**Comment by trazyn** [comment]
在设置里面可以改端口好
![screen shot 2017-10-17 at 9 31 09 pm](https://user-images.githubusercontent.com/1774898/31667613-817c69ba-b382-11e7-86c3-a2e0b300f4fc.png)

**Comment by FFlowerS** [comment]
对，我发现是端口占用了，然后嘛……
![snipaste_2017-10-17_21-32-21](https://user-images.githubusercontent.com/8475161/31667703-cb370f4c-b382-11e7-93c6-8ad2b7e54257.png)

就一直转啊转（

**Comment by FFlowerS** [comment]
![snipaste_2017-10-17_21-39-02](https://user-images.githubusercontent.com/8475161/31667993-8a323c46-b383-11e7-983a-e98ced123d01.png)

嗯，点完确定还一张

**Comment by trazyn** [comment]
IP被官方未知原因暂时ban了，改hosts #20 可破

**Comment by FFlowerS** [comment]
十分感谢！

**Comment by trazyn** [comment]
不客气 🤗
