### ISSUE TITLE
Mac 上Top 页面滑动不流畅

### ISSUE THREAD

**Issue by JeyPiao** [trazyn/ieaseMusic#41]
TOP页面滑动基本是瘫痪状态

**Comment by trazyn** [comment]
滚动是左右滑动，滚轮默认是nature模式

**Comment by gonejack** [comment]
四周没有圆角不够Mac

**Comment by gonejack** [comment]
![99083982-69dd-4708-9735-29a7ae1977f3](https://user-images.githubusercontent.com/2720676/31709944-2865d59c-b426-11e7-9c63-feb0258cd493.png)
上直下弯啊

**Comment by gonejack** [comment]
另外状态栏图标双击应该要执行Toggle main window才对

**Comment by trazyn** [comment]
状态栏图标有点丑，我都是隐藏的，还真没怎么注意过啊😂

**Comment by gonejack** [comment]
怎丑得过Dock图标，我都打算用Spotlight启动好了（笑▽笑）

**Comment by trazyn** [comment]
@gonejack 瞎说，Dock图标黄黄的多有爱多有内涵啊😆 不丑不丑
