### ISSUE TITLE
Windows版本有希望吗

### ISSUE THREAD

**Issue by 20171213** [trazyn/ieaseMusic#418]

**Comment by icimence** [comment]
electron框架，点到为止

**Comment by ameaninglessname** [comment]
electron是跨平台的框架，那就稳了。
求Windows版本!~!~!~
我也超喜欢J.Fla的！！！

**Comment by AmayerGogh** [comment]
need windows

**Comment by ghsgz** [comment]
哈哈哈，请自己编译

**Comment by wanf3ng** [comment]
自己去编译一份试试

**Comment by muxinxy** [comment]
这里有大佬做出来了
https://github.com/trazyn/ieaseMusic/issues/35#issuecomment-504889488
