### ISSUE TITLE
Notification loop when playing a unavailable album

### ISSUE THREAD

**Issue by 4faramita** [trazyn/ieaseMusic#44]
When I tried to play a unavailable album, the program will keep looping through the album, and sending notifications at the same time. The CPU resource will soon run out.

Maybe set a auto-stop after one loop?

**Comment by trazyn** [comment]
国内？国外？
国外的话需要改hosts，1.0.0存在这个问题，会跳过有版权问题的歌曲

**Comment by 4faramita** [comment]
@trazyn It's not the unavailability, the problem is the loop.

**Comment by trazyn** [comment]
![screen shot 2018-06-29 at 10 59 24 pm](https://user-images.githubusercontent.com/1774898/42099524-31a07d46-7bf0-11e8-95f5-bbeca57687fc.png)
