### ISSUE TITLE
Mac版卸载后原生的云音乐客户端登录不了

### ISSUE THREAD

**Issue by Yaanco** [trazyn/ieaseMusic#445]
我在Mac上，当卸载了ieaseMusic后，原生的网易云音乐登录不上了，手机号，扫码和邮箱都不可以！
<img width="1114" alt="Screen Shot 2019-11-30 at 9 10 20 PM" src="https://user-images.githubusercontent.com/49360816/69900992-ef1ec180-13b5-11ea-9b52-0205b7ec7b30.png">

**Comment by speedecho** [comment]
把 host 修改的那几行地址删除试试

**Comment by Yaanco** [comment]
> 把 host 修改的那几行地址删除试试

更新了下最新版本可以了
