### ISSUE TITLE
求支持Windows版本

### ISSUE THREAD

**Issue by WhatDamon** [trazyn/ieaseMusic#466]
# 求支持Windows版本啊
windows的用户群体比Linux和macOS多的多，
如果不发布Windows版本，基本没人知道
# 问题
如果您问发布在Windows上会不会被网易云看上
回答一下，不商业，问题基本不大，人家Listen 1都敢，不用太担心
如果您的电脑是非Windows系统，测试什么的，怎么办
测试方面装类似Wine的软件，其他问题网上基本都有
后面我想不到有什么问题了

**Comment by hongvest** [comment]
WhatDamon <notifications@github.com> 於 2020年6月15日 週一 下午7:29 寫道：
