### ISSUE TITLE
一打开软件就不停地切歌、弹通知栏小框

### ISSUE THREAD

**Issue by dccxi** [trazyn/ieaseMusic#47]
![screen shot 2017-10-18 at 5 35 24 pm](https://user-images.githubusercontent.com/7568396/31743889-c6a21f6e-b42a-11e7-8ce9-393058fd5f89.png)

macOS High Sierra (17A362a)
安装包为：ieaseMusic-1.0.1-mac.dmg

**Comment by trazyn** [comment]
参考#4 海外解锁
