### ISSUE TITLE
可以添加一个更改Dock图标颜色的功能么

### ISSUE THREAD

**Issue by x86vk** [trazyn/ieaseMusic#48]
如题，这个Dock icon在黑底下真的不太好看= = 
而且由于我的屏幕是HiDPI的，这个图标没做适配，比一般的图标要小。
![2017-10-19 09-17-14](https://user-images.githubusercontent.com/12608529/31749725-5b14fcb0-b4ae-11e7-8e65-1057263ca0fa.png)

**Comment by trazyn** [comment]
你的是什么桌面环境啊，图标应该是readme里面黄色那个，这个是小的黑色的是状态栏图标，是可以隐藏的

**Comment by x86vk** [comment]
啊，我意思就是状态栏图标。可能表述有些问题_(:з」∠)_
隐藏是可以隐藏，但个人比较喜欢让它显示出来，这样控制起来比较方便
桌面环境是Gnome 3.24.2

**Comment by x86vk** [comment]
其实就是希望大大能像electronic-wechat一样，做个ChangeIconColor的功能。
![2017-10-19 09-59-56](https://user-images.githubusercontent.com/12608529/31750723-6022a314-b4b4-11e7-8d0f-f22c0dd9b523.png)

**Comment by trazyn** [comment]
ok
