### ISSUE TITLE
真丑。。。。

### ISSUE THREAD

**Issue by janryWang** [trazyn/ieaseMusic#5]
界面简直乱来，不该有阴影的地方乱加阴影，色彩太杂，无层次，动画不平滑，太突兀

**Comment by trazyn** [comment]
好了知道了

**Comment by MyFaith** [comment]
莫非这是传说中的喷子？

**Comment by kevinaskin** [comment]
> 对**没有之一**吓到了

**Comment by niices** [comment]
只能说审美不同。。。直接上来打脸的老铁还是要提高一下姿势水平。。。

**Comment by ken113** [comment]
看到几个commit都是删动画的，写的 'reduce cpu usage' 不知道lz上面 说的动画是啥，看起来像喷子

**Comment by wqqdhero** [comment]
嫌丑就不要用啊.....
免费给你用还要喷

**Comment by blackcater** [comment]
过分了，免费的，你要求也太高了吧！

**Comment by Huang-Jinxian** [comment]
### 手机上看到的，特地打开电脑只为回复你
>请嘴下留情，每个人都有每个人的喜好和审美，你不喜欢可以说不符合你的审美，但请不要喷人，更何况别人写程序首先是给自己用的，开源出来给大家用也是一片好心。说句不好听的，你能写一个符合你要求的开源出来给大家吗？不行就别bb！！！对别人开源的作品要求这么高，那你怎么不去找外包定制一个，第一次在github上看到喷别人的，你可以吐槽和建议，但请不要喷人，这样很打消作者开源热情的。

**Comment by crywolfx** [comment]
提个Issuse就为了说这个？失了智吧你

**Comment by xiaopin** [comment]
既然都开源了，不符合你的审美，你自己把它改成符合你的审美就行了嘛，反正我是来看代码的

**Comment by lh4111** [comment]
丑可以提PR嘛 干嘛提issue

**Comment by guguji5** [comment]
我倒是觉得挺绚丽，怎么搞的？？

**Comment by Itherma** [comment]
该死的喷子

**Comment by ChasLui** [comment]
MD智障

**Comment by Hongbo-Miao** [comment]
还行，不过还会变的更好的。放个截图，过半年一年大家再回来比较。加油
![image](https://user-images.githubusercontent.com/3375461/33757864-e0af3a2e-dbb0-11e7-9606-77a920e89552.png)

**Comment by Hongbo-Miao** [comment]
挺好的，不过还会变的更好的。放个截图，过半年一年大家再回来比较。加油！
![image](https://user-images.githubusercontent.com/3375461/33757864-e0af3a2e-dbb0-11e7-9606-77a920e89552.png)

**Comment by Hongbo-Miao** [comment]
挺好的，但不要止步于此，还会变的更好的。放个截图，过半年一年大家再回来比较。加油！

![image](https://user-images.githubusercontent.com/3375461/33757864-e0af3a2e-dbb0-11e7-9606-77a920e89552.png)
