### ISSUE TITLE
在Archlinux的AUR中添加该软件包

### ISSUE THREAD

**Issue by farawaaay** [trazyn/ieaseMusic#51]
如果能够在Archlinux的AUR中添加该软件包，安装会变得很便利

**Comment by farawaaay** [comment]
希望能在Archlinux的AUR中添加该软件包

**Comment by hr567** [comment]
已有用户添加
https://aur.archlinux.org/packages/iease-music

**Comment by farawaaay** [comment]
好的！我之前没有发现。建议在README中告知一下。

**Comment by trazyn** [comment]
Ok
