### ISSUE TITLE
这个linux的api好像对海外用户友善一些..我这里不知道为啥歌曲获取到的信息大多数为空

### ISSUE THREAD

**Issue by wjm2038** [trazyn/ieaseMusic#57]
项目地址:`https://github.com/metowolf/Meting`
win 客户端

   本地api请求网址: http://localhost:10086/api/player/related/429261494/17241

    response:
    {
        "users": [],
        "artists": [],
        "playlists": []
    }

**Comment by trazyn** [comment]
如果你是用于开发调试的话，可以在终端看到debug信息的输出

**Comment by wjm2038** [comment]
主要是node不太熟练😂😂win版本打包一直没成功过

**Comment by trazyn** [comment]
npm run dev的时候在终端里面可以看到所有的debug信息，像这种全是空的一般是api部分出错了

**Comment by wjm2038** [comment]
谢谢,我先试试

**Comment by wjm2038** [comment]
npm WARN jss-compose@4.0.0 requires a peer of jss@^8.0.0 but none is installed. You must install peer dependencies yourself.
    npm WARN jss-expand@4.0.1 requires a peer of jss@^8.0.0 but none is installed. You must install peer dependencies yourself.
    npm WARN jss-global@2.0.0 requires a peer of jss@^8.0.0 but none is installed. You must install peer dependencies yourself.
    npm WARN jss-preset-default@3.0.0 requires a peer of jss@^8.0.0 but none is installed. You must install peer dependencies yourself.
    npm WARN jss-camel-case@5.0.0 requires a peer of jss@^8.0.0 but none is installed. You must install peer dependencies yourself.
    npm WARN jss-default-unit@7.0.0 requires a peer of jss@^8.0.0 but none is installed. You must install peer dependencies yourself.
    npm WARN jss-extend@5.0.0 requires a peer of jss@^8.0.0 but none is installed. You must install peer dependencies yourself.
    npm WARN jss-nested@5.0.0 requires a peer of jss@^8.0.0 but none is installed. You must install peer dependencies yourself.
    npm WARN jss-vendor-prefixer@6.0.0 requires a peer of jss@^8.0.0 but none is installed. You must install peer dependencies yourself.
    npm WARN jss-props-sort@5.0.0 requires a peer of jss@^8.0.0 but none is installed. You must install peer dependencies yourself.
    npm WARN url-loader@0.5.9 requires a peer of file-loader@* but none is installed. You must install peer dependencies yourself.

我明明都安装过了 。。。
     npm install -g jss@^8.0.0
    + jss@8.0.0
    updated 1 package in 1.672s

**Comment by trazyn** [comment]
warn部分不用理会
