### ISSUE TITLE
网络代理设置

### ISSUE THREAD

**Issue by xebcxc** [trazyn/ieaseMusic#58]
Ubuntu版本支持设置网络代理吗？

**Comment by trazyn** [comment]
如果是海外解锁请参考#4

**Comment by syhily** [comment]
@trazyn 目前的主要使用环境是公司内网，访问外部节点均需要配置代理，wewechat是可以读取 mac 的默认代理配置，但是 ieaseMusic 似乎不走代理，所以会影响使用。

**Comment by nondanee** [comment]
正好我那边也有人提，我来强答
@syhily 
其实electron窗口默认是走系统代理的，不需要加额外代码，因为本质就是个chromium。
我猜想wewechat基于微信web应该是所有请求都通过xhr发起，全部可以走浏览器代理，
而ieaseMusic还自带了个api服务器跑在后台，后台服务不归这个chromium窗口管，而node是无视系统代理的，需要自己设置。
所以你认为wewechat读取了系统代理而ieaseMusic没有，其实都走了代理，
只是因为api没走代理连数据都没有，如果api返回数据了，窗口内所有显示的图片，播放的音频都走代理
具体的话，因为代码不是我写的，哪里请求了我就不知道了
我只知道网易云[Binaryify/NeteaseCloudMusicApi](https://github.com/Binaryify/NeteaseCloudMusicApi)这个api怎么改
[util/util.js](https://github.com/Binaryify/NeteaseCloudMusicApi/blob/master/util/util.js)
line 43-45
```
      hostname: host,
      method: method,
      path: path,
````
改成
```
      host: <proxy host>,
      port: <proxy port>,
      method: method,
      path: "http://music.163.com" + path,
```

**Comment by mrmeisen** [comment]
我用wewechat可以使用系统代理，但是ieaseMusic无法读取代理，所以一直卡在登录页面。是因为我是Ubuntu吗？

**Comment by syhily** [comment]
@nondanee 嗯，今天下午看了一下，的确是 Binaryify/NeteaseCloudMusicApi

**Comment by nondanee** [comment]
@mrmeisen 解释了啊，前端(音频播放图片显示等)都自动走代理，node后台(歌单详情专辑歌手信息之类)没设置过都不走代理
登录接口是后台管的，就没走代理，应该跟ubuntu没有关系

**Comment by nondanee** [comment]
@syhily 很明显啊，readme就写了的

**Comment by nondanee** [comment]
@trazyn 要大佬不加个设置？（估计有点麻烦，要重造轮子，不能直接用submodule了）

**Comment by Towdium** [comment]
Emmmm 我这边用proxychains配置代理，海外党解锁亲测可用  
发行版Manjaro，不过linux应该都可以用

**Comment by syhily** [comment]
@trazyn I don't think this could be marked non-issue label.
A configurable proxy function should be supported.

**Comment by trazyn** [comment]
增加了代理设置，只作用于第三方曲库，打算去掉目前的API依赖重新撸

**Comment by vcfvct** [comment]
公司内网用户怎么设置代理, 求instruction! 谢谢!

**Comment by trazyn** [comment]
Close https://github.com/trazyn/ieaseMusic/commit/41fa408011eabbd58baa2b4dbbaf2a16575d69b6
