### ISSUE TITLE
这 UI 真的享受不了啊

### ISSUE THREAD

**Issue by whorusq** [trazyn/ieaseMusic#62]
动画风格确实够 diao炸天，但是杂乱，风格、布局一点不 mac ，不够简约、易用。
@trazyn

**Comment by trazyn** [comment]
没想过所有人都喜欢，也没要求过所有人都喜欢，自己喜欢就好不懂这个issue有什么意义

**Comment by whorusq** [comment]
同样是做软件的，只是提一下个人看法和建议而已，issues 没说只是反馈问题的吧 ~
