### ISSUE TITLE
[BUG] 部分歌曲播放某个时间之后卡住

### ISSUE THREAD

**Issue by Yves0** [trazyn/ieaseMusic#64]
在 ArchLinux 和 Ubuntu 17.04 上都会，例如 Isaac Gracie 的 Reverie 播放到 1:08 的时候就停止播放了。

另外播放器用着有点卡，虽然看起来很漂亮，希望体验能更好点

**Comment by trazyn** [comment]
目前异常部分基本全是网络错误，错误alter阻塞进程确实不友好，需要进行优化

**Comment by Yves0** [comment]
现在暂时只能用回 musicbox 了，因为收藏的歌单中不少都是播放一半就放不了了。不过还是非常感谢，希望能完善这个播放器。

**Comment by eaglexiang** [comment]
同样出现这样的错误，不过这样的Bug官方客户端也存在。

**Comment by AlexanderOnly** [comment]
同样出现这个错误 但是我很喜欢这个播放器😄 非常感谢作者 希望能进一步优化

**Comment by trazyn** [comment]
5秒超时，无搜索结果跳到到下一首
