### ISSUE TITLE
手机号登录不支持国外手机号

### ISSUE THREAD

**Issue by laserroger** [trazyn/ieaseMusic#65]
RT，用美国手机号没办法登录

**Comment by trazyn** [comment]
云音乐的官网上可以使用海外的手机登陆么

**Comment by trazyn** [comment]
@laserroger https://github.com/trazyn/ieaseMusic/releases/latest 试试

**Comment by laserroger** [comment]
@trazyn 我这里测试还是不太行

**Comment by trazyn** [comment]
之前登录不上是少了国家码 你登录时手机号前面加上国家码比如 +86131xxxxxxxx

**Comment by laserroger** [comment]
不是的。。我把各种组合都尝试过了

**Comment by funabashi-cn** [comment]
请问如何用网易邮箱登录呢

**Comment by trazyn** [comment]
@funabashi-cn 目前邮箱是无法登陆的，可以用邮箱绑定手机号然后再进行登陆

**Comment by trazyn** [comment]
@laserroger 你的账号在官网上能登陆不，官网上打开控制台输入`window.asrsea`然后断点看看输入参数，没有国外的手机号所以没法自测了
