### ISSUE TITLE
Search 功能失效

### ISSUE THREAD

**Issue by Germxu** [trazyn/ieaseMusic#70]
home下面的search按钮没有任何功能？

**Comment by trazyn** [comment]
home 下面没有search按钮啊🤣

**Comment by Germxu** [comment]
<img width="852" alt="2017-11-06 5 35 01" src="https://user-images.githubusercontent.com/20300863/32434761-fe05d114-c319-11e7-9c6e-8ac0a6a25789.png">
就是这个下面的Search啊，不是前面按钮下的搜索（这个可用，好像音乐十之八九又搜不到）

还有一个问题， 这个客户端不能兼容AirPods， 不能做到取下暂停， 似乎是个网页版的播放器。。。

**Comment by trazyn** [comment]
搜索是官方的接口，官方的搜到那就是搜不到了，AirPods适配问题可以到(electron/electron)[https://github.com/electron/electron]去提问

**Comment by Germxu** [comment]
图上这个Search无任何功能？

**Comment by trazyn** [comment]
![2017-11-06 21 14 37](https://user-images.githubusercontent.com/1774898/32442796-45bcafbc-c2c2-11e7-846f-9d3582fa7754.gif)
@Germxu 不知道你用的什么版本

**Comment by Germxu** [comment]
哦哦, 我的不是最新版, 我在推荐网站直接下载的, 不好意思

**Comment by Germxu** [comment]
哦哦, 我的不是最新版, 我在推荐网站直接下载的, 不好意思
