### ISSUE TITLE
不会写苹果软件，提几个小建议

### ISSUE THREAD

**Issue by KItkim160** [trazyn/ieaseMusic#72]
请求大大装个音量条上去，然后就是来个歌词功能啊。桌面歌词或者单曲的歌词也行啊。界面打call，屌炸了。仰望大佬。还有就是，进度条太细了。。。不好操作。还有，为啥我自己的单曲不能够单独看。放歌的时候我不想看列表，就想看单曲，没有歌词，封面也行啊。有个小bug，我切换歌曲的时候，进度条会延迟几秒回到0

**Comment by trazyn** [comment]
最近上班有点忙，没什么时间去做优化

**Comment by trazyn** [comment]
鼠标移入调整进度条宽度https://github.com/trazyn/ieaseMusic/commit/8ab64bf9820d952635137e8eb0d69bf872be6360

**Comment by KItkim160** [comment]
明天试试新版本

**Comment by trazyn** [comment]
歌词 https://github.com/trazyn/ieaseMusic/commit/3e2cda153b83b18e5b142d2572c37c39a972beba

**Comment by trazyn** [comment]
进度条 #104
