### ISSUE TITLE
这个文字下面的黑色背景似乎有点难看

### ISSUE THREAD

**Issue by VeTsgG** [trazyn/ieaseMusic#73]
[https://github.com/trazyn/ieaseMusic/blob/master/screenshots/player.png](url)

**Comment by VeTsgG** [comment]
![default](https://user-images.githubusercontent.com/12571320/32503184-8ea0ab60-c417-11e7-8f28-69e75463ad79.jpg)

**Comment by VeTsgG** [comment]
![1](https://user-images.githubusercontent.com/12571320/32503575-8e3fe248-c418-11e7-99bd-ef0145108115.jpg)

**Comment by trazyn** [comment]
关于windows的都可以在 #35 提问
