### ISSUE TITLE
bug：bad audio src

### ISSUE THREAD

**Issue by howie6879** [trazyn/ieaseMusic#76]
搜索风清扬 听的时候报这个错 然后会一直显示 播放这首歌曲的提示条：
<img width="737" alt="screen shot 2017-11-11 at 22 39 08" src="https://user-images.githubusercontent.com/17047388/32690423-1dd5e326-c6bc-11e7-88ee-8edc3d8c87fe.png">

**Comment by howie6879** [comment]
这首歌 无版权

**Comment by trazyn** [comment]
跟单id是多少

**Comment by trazyn** [comment]
![screen shot 2017-11-14 at 1 17 33 am](https://user-images.githubusercontent.com/1774898/32739532-1897af68-c8db-11e7-83d2-93e3972959b0.png)
有些曲库的API比较老，所有有些歌曲是搜索不到的

**Comment by howie6879** [comment]
恩恩  问题就是会重复循环提醒 正在播放 ××× 一直循环

**Comment by trazyn** [comment]
会自动进入到下一首，如果一直没有就会循环，这里确实需要做些体验上的优化

**Comment by howie6879** [comment]
是的 单曲情况下 若无版权无法播放 就会一直无限循环

**Comment by trazyn** [comment]
基本所有歌曲都能播放了
