### ISSUE TITLE
断开网络之后再连接上会一直加载~

### ISSUE THREAD

**Issue by moguocan** [trazyn/ieaseMusic#77]

**Comment by trazyn** [comment]
目前API使用的是第三方的库，感觉不太稳定，可能会去做些其他的尝试

**Comment by trazyn** [comment]
断开网络然后重新连接网络

![2017-12-05 23 29 10](https://user-images.githubusercontent.com/1774898/33615119-39d6ac7a-da14-11e7-9306-76ca2497ae0a.gif)
