### ISSUE TITLE
linux 版，桌面 dock 无法正确显示图标

### ISSUE THREAD

**Issue by lemos1235** [trazyn/ieaseMusic#78]
系统：Manjaro 17.0.6-EOL
桌面：gnome
桌面主题：OSX-Arc-White
图标：Arc-OSX-P

![image](https://user-images.githubusercontent.com/23135552/32762931-6e93a01e-c937-11e7-9a3e-855bafb88ed1.png)

PS：启动器里是正常的。

**Comment by lemos1235** [comment]
还有一点，正常模式下貌似是无法进入歌曲详情页面。

**Comment by trazyn** [comment]
有个issue有人提到过gnome下的图标修改，第二个歌曲是没有详情页面的，整个应用设计都是围绕歌单展开的

**Comment by lemos1235** [comment]
What a pity

**Comment by trazyn** [comment]
https://github.com/trazyn/weweChat/issues/39

**Comment by lemos1235** [comment]
![image](https://user-images.githubusercontent.com/23135552/32822084-c3280c5c-ca11-11e7-8c0e-5829c76ca8b9.png)
实际上启动的时候显示的是灰色的图标。所以？

**Comment by trazyn** [comment]
会有一个api的后台进程
