### ISSUE TITLE
下载问题

### ISSUE THREAD

**Issue by jackliuqinfen** [trazyn/ieaseMusic#79]
怎么下载都下载不了
求提供百度网盘地址
好想用一下试试
不管是翻墙下载还是不翻墙下载
都是1KB/S，很尴尬呀
使用Homebrew 也是失败了好几次
更换电脑更换网络都试过了还是不行，求解

**Comment by trazyn** [comment]
翻墙可以正常下载，小众软件，不准备广而告之，避免太多谓的issue
