### ISSUE TITLE
脑洞真的很大，无法自拔的美丽

### ISSUE THREAD

**Issue by TIL-MICE** [trazyn/ieaseMusic#85]
不得不说的美，but，is Chinese too low？（实用性，待改进）为毛除了歌曲列表 连个中文都看不到，即便 那几个单词真的很简单，by the way，提个建议，logo如果可以 please choose another one（黄色 少儿不宜啊）, thanks. ...编不下去了，能不能加授权登录，我一直都是新浪微博授权登录，没真的创建过账号，不能愉快的装逼了，author 辛苦了。。。。

**Comment by trazyn** [comment]
小众软件，不准备广而告之，第三方的会持续进行集成，前面有事情，后面会持续就行优化
