### ISSUE TITLE
1.0.3 版本在Ubuntu 16.04.3 LTS上启动报错

### ISSUE THREAD

**Issue by ossphil** [trazyn/ieaseMusic#86]
如图示，然后就会一直停留在启动界面。

![screenshot from 2017-11-23 15-36-31](https://user-images.githubusercontent.com/11551949/33162464-94249e6c-d064-11e7-9eaa-b990d4d89ec3.png)
![screenshot from 2017-11-23 15-37-07](https://user-images.githubusercontent.com/11551949/33162470-9a3cfc22-d064-11e7-8d65-e15e3356d90a.png)

**Comment by trazyn** [comment]
海外么，访问被ban了

**Comment by ossphil** [comment]
没有，用代理，关了代理也出现上面的错误

**Comment by trazyn** [comment]
这个代理目前不是很稳定，不使用全局代理的情况下，国内多数情况下直接访问是不会有问题的，`socket hang up`这个基本可以确定是网络问题，导致无法正常访问

**Comment by ossphil** [comment]
那我再排查一下

**Comment by willshion** [comment]
ubantu 1604.3  zhijie jieya keyi

**Comment by ossphil** [comment]
1.0.7版本可以了
