### ISSUE TITLE
请问大佬能否把last.fm整合进来啊

### ISSUE THREAD

**Issue by SIDmao** [trazyn/ieaseMusic#87]
如果能的话
那听歌的频率什么的就都能同步到last.fm上了
😂

**Comment by trazyn** [comment]
ok 只是最近比较忙，已经在todo里面了

**Comment by trazyn** [comment]
https://github.com/trazyn/ieaseMusic/commit/f16bc91ca778e2cf1a47c61b69da05fab3bbd55b
