### ISSUE TITLE
在播放比较大的 playlist 时，会在播放一定数目的曲目后卡住

### ISSUE THREAD

**Issue by nasyxx** [trazyn/ieaseMusic#89]
经常播放10几首曲子后，卡住不自动播放下一首，手动点击下一首才会继续播放

**Comment by loosewan** [comment]
+1

**Comment by trazyn** [comment]
给个歌名看看或者playlist

**Comment by nasyxx** [comment]
<img width="852" alt="screen shot 2017-11-29 at 1 02 42 am" src="https://user-images.githubusercontent.com/5007613/33333118-09f1d50c-d4a1-11e7-9598-463825ef2b5f.png">

比如这个。。。还有好多的，我这里几个比较长的几个都会卡

**Comment by trazyn** [comment]
卡住的时候给个控制台错误看看 你下一个最新的1.06 所有歌曲不会拿缓存 重新请求避免链接过期

**Comment by nasyxx** [comment]
刚好，刚刚卡住。

本来应该到播放第六首了，但是，图上可以看到进度条在第五首的倒数第二秒卡住了，然后第六首就没有加载。

<img width="852" alt="screen shot 2017-11-29 at 1 26 57 am" src="https://user-images.githubusercontent.com/5007613/33334327-6ff3f08a-d4a4-11e7-8771-982a6d66dc81.png">

<img width="852" alt="screen shot 2017-11-29 at 1 25 56 am" src="https://user-images.githubusercontent.com/5007613/33334289-4e8b7620-d4a4-11e7-841d-103290778ed5.png">

**Comment by trazyn** [comment]
嗯下最新的就好了，这个版本URL没有encode会出现404，在老一个版本会存在缓存问题，下1.0.6就好了

2017-11-29 1:28 GMT+08:00 Nasy <notifications@github.com>:

**Comment by nasyxx** [comment]
谢谢，因为是 homebrew 安的，没注意更新了，麻烦啦。等我试试看

**Comment by trazyn** [comment]
有空在去更新 `homebrew` 了
