### ISSUE TITLE
Error code -43

### ISSUE THREAD

**Issue by joeybuddy** [trazyn/ieaseMusic#9]
version: 0.0.3
os: macOS High Sierra 10.13

ieaseMusic.app 往 Applications 里面拖的时候有报错。

<img width="399" alt="error" src="https://user-images.githubusercontent.com/10774846/30955121-2f139304-a3f8-11e7-9dbb-ef1bb69cd435.png">

**Comment by trazyn** [comment]
看起来是Finder的问题 `killall Finder` 在看看，或者logout 或者重启
https://macperformanceguide.com/blog/2016/20160203_0932-Finder-FileNotFound.html

**Comment by joeybuddy** [comment]
嗯，sorry 这是个系统错误，跟应用无关
