### ISSUE TITLE
爱不释手！弱弱的问一句

### ISSUE THREAD

**Issue by yangxiaobinhaoshuai** [trazyn/ieaseMusic#90]
还有loading 界面能不能加个取消按钮... loading 失败的时候有点不知所措

还有时常会弹窗显示jsError，显示以下内容

A JavaScript error occurred in the main process
Uncaught Exception:
Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:581:26)

**Comment by trazyn** [comment]
音量控制键盘的上下键可以调节

**Comment by trazyn** [comment]
错误是网络错误，目前国内使用现在是很少会被官方高频访问限制的
