### ISSUE TITLE
last.fm 相关问题

### ISSUE THREAD

**Issue by dalecgu** [trazyn/ieaseMusic#91]
1. 登录 last.fm 时，第二个输入框应该是 Password 。见下图。
![image](https://user-images.githubusercontent.com/7344018/33591434-870798aa-d9c0-11e7-817f-33e145d6caf5.png)
2. 下面那个 Connect 的按钮好像也有点问题，上面两个输入框填了内容以后，这个按钮没有变成可点击的状态。点了这个按钮以后，先变成了 Connecting ，然后又变回了 Connect 。不清楚是 UI 的问题还是授权登录的过程中有错。

**Comment by trazyn** [comment]
额  确实是写错了，按钮逻辑是`username`和`password`都不为空时候按钮可点击，链接过程中禁用按钮显示为`Connecting`，链接成功后显示为`Connected`

![2017-12-05 14 24 12](https://user-images.githubusercontent.com/1774898/33592915-08eda556-d9c8-11e7-9cee-e24fc41bcd4b.gif)

**Comment by dalecgu** [comment]
补上我这边的视频，点了 Connect 按钮以后没有成功连接。

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/7344018/33593234-7a48e5a2-d9c9-11e7-8081-53cd18cb25d5.gif)

另外，connect 拼错了😓

**Comment by trazyn** [comment]
你的账号密码在官网上可以正常登陆么，我换了个账号测试了下登陆时正常的，编辑器用的`vim` `supertab`自动联想，没怎么注意拼写错误😂

**Comment by dalecgu** [comment]
可以的，我也以为是我账号密码记错了，特意去试了一下。我一会儿换个账号再测一下。

**Comment by trazyn** [comment]
换个三个号登陆都没问题

**Comment by dalecgu** [comment]
我找到问题了，和ieaseMusic无关。我是很久以前注册的Last.FM账号，密码比较简单。在它的主页上可以正常登录，但是用于第三方授权登录就不可以。改了一下密码就行了。耽误你时间了，真抱歉！
