### ISSUE TITLE
一點建議

### ISSUE THREAD

**Issue by Fe1IYang** [trazyn/ieaseMusic#93]
希望使窗體可調節大小，現在這樣的窗體不太適合在曲目很多的歌單內尋找歌曲。

**Comment by trazyn** [comment]
确实是个问题

**Comment by trazyn** [comment]
![2017-12-10 00 58 22](https://user-images.githubusercontent.com/1774898/33797564-53f557d0-dd45-11e7-953f-2f3129314ca5.gif)
