### ISSUE TITLE
两个很影响体验的bug

### ISSUE THREAD

**Issue by pharra** [trazyn/ieaseMusic#95]
1、打开第二次会报错，看log是监听端口被占用？
打开第二次不应该是显示被隐藏的窗口吗
2、在cinnamon里最小化后，点击右边状态栏不能显示，所以我在菜单栏打开第二次(在菜单栏找到了显示主窗口，所以是不能点击显示emmmm，很难受）

建议：
_打开后不要默认播放音乐_（在设置找到了）

设置在主界面没找到，在菜单栏的preference里面，emmm，跟我平时的使用习惯不太一样

话说menu bar iconn有点小（cinnamon两倍高分辨率）
官方则是好像不支持高分辨率了，点个赞

**Comment by trazyn** [comment]
linux？`mac`不会重复打开，默认自动播放在设置里面可以关闭

**Comment by pharra** [comment]
@trazyn 是的，arch linux  cinnamon

**Comment by trazyn** [comment]
1 #138
