### ISSUE TITLE
1.0.9 打開就顯示報錯

### ISSUE THREAD

**Issue by xiyionxiong** [trazyn/ieaseMusic#96]
![deepinscrot-5640](https://user-images.githubusercontent.com/14977994/33861754-781d21e8-df1a-11e7-8265-3cb1fa052acf.png)

然後一直顯示 點擊cancle， 主界面一直顯示加載中。。。。
![deepinscrot-5805](https://user-images.githubusercontent.com/14977994/33861779-97677dbe-df1a-11e7-9d84-2537f9793efb.png)

**Comment by trazyn** [comment]
网络原因导致更新检测失败，首页也无法打开

**Comment by updater1234** [comment]
我是打开报错，但进得了软件。这又是什么回事？有什么解决方法

**Comment by trazyn** [comment]
打开的时候会自动检测更新，更新源在github relase 网络问题

**Comment by updater1234** [comment]
那么能在软件里添加一个关闭自动检测更新的功能吗？这样感觉好不爽

**Comment by trazyn** [comment]
嗯可以

**Comment by updater1234** [comment]
更新了，谢谢。
